### ISSUE TITLE
Depth Image Undistortion

### ISSUE THREAD

**Issue by cdforigua05** [facebookresearch/projectaria_tools#11]
Hi,

I'm interested in obtaining annotations, particularly the depth maps, in a pinhole rectified format. I'm aware that there are some code snippets in the documentation and the Jupyter notebook tutorial for rectifying the fisheye format of the raw RGB sensor. However, when I attempt to retrieve the rectified depth map using the provided code, I encounter an error. Is there a code snippet available for rectifying the depth modality without losing the distance information? The provided code rectifies the depth map only for visualization purposes, causing the information to transition from distance to color.

Thank you for your time and collaboration.

**Comment by SeaOtocinclus** [comment]
Hello,

Here is what you can do for ASE `Aria Synthetic Environments)`
- see the almost last line for the work around

```
from projectaria_tools.projects import ase
device = ase.get_ase_rgb_calibration()

frame_id = str(frame_idx).zfill(7)

rgb_path = rgb_dir / f"vignette{frame_id}.jpg"
depth_path = depth_dir / f"depth{frame_id}.png"
instance_path = instance_dir / f"instance{frame_id}.png"

rgb = Image.open(rgb_path)
depth = Image.open(depth_path)
instances = Image.open(instance_path)

from projectaria_tools.core import data_provider, calibration
pinhole = calibration.get_linear_camera_calibration(
    device.get_image_size()[0],
    device.get_image_size()[1],
    device.get_focal_lengths()[0])

raw_image = np.array(rgb)
undistorted_image = calibration.distort_by_calibration(raw_image, pinhole, device)

raw_image = np.array(instances)
undistorted_image = calibration.distort_by_calibration(raw_image, pinhole, device)

# raw_image = np.array(depth) # Will not work
raw_image = np.array(depth).astype(np.float32) # WILL WORK
undistorted_image = calibration.distort_by_calibration(raw_image, pinhole, device)
```

<img width="1046" alt="image" src="https://github.com/facebookresearch/projectaria_tools/assets/74376766/3734b17a-9dcc-4a67-8303-ecdf9facdd04">

If you are in ADT `Aria Digital Twin`
- I will let @YLouWashU chime in

**Comment by cdforigua05** [comment]
Thank you so much @SeaOtocinclus !
The code snippet helped me to solve the problem.

**Comment by anassmu** [comment]
hello everyone, i have a question , does get_linear_camera_calibration works for all depth and rgb images in the ASE dataset ?what is the fourth parameter of the function (which is a string), even though while using get_linear_camera_calibration  to undistort the images, the pointcloud is still distorted, any help, maybe with the distortion process or the pointcloud generation? thanks a lot :)
![lolol](https://github.com/facebookresearch/projectaria_tools/assets/36223316/9ba0f276-88dd-4ba4-9d98-67c564b809fe)
![Screenshot 2023-12-13 141628](https://github.com/facebookresearch/projectaria_tools/assets/36223316/0bcfaa18-a5b1-4795-a26a-f552cb269c27)
![Screenshot 2023-12-13 141639](https://github.com/facebookresearch/projectaria_tools/assets/36223316/7e0be505-a48a-49d9-bfb7-cfa495d27d00)


`
# read data
from projectaria_tools.projects import ase
from projectaria_tools.core import data_provider, calibration

device = ase.get_ase_rgb_calibration()
frame_id = str(frame_idx).zfill(7)

rgb_path = rgb_dir / f"vignette{frame_id}.jpg"
depth_path = depth_dir / f"depth{frame_id}.png"
instance_path = instance_dir / f"instance{frame_id}.png"

rgb = Image.open(rgb_path)
depth = Image.open(depth_path)
instances = Image.open(instance_path)

# undistort data
pinhole = calibration.get_linear_camera_calibration(
    device.get_image_size()[0],
    device.get_image_size()[1],
    device.get_focal_lengths()[0],device.get_label())

raw_image = np.array(rgb)
undistorted_rgb = calibration.distort_by_calibration(raw_image, pinhole, device)

raw_image = np.array(instances)
undistorted_instances = calibration.distort_by_calibration(raw_image, pinhole, device)

raw_image = np.array(depth).astype(np.float32) # WILL WORK
undistorted_depth = calibration.distort_by_calibration(raw_image, pinhole, device)

# Convert images to numpy arrays
rgb_array = np.array(rgb)
instances_array = np.array(instances)
depth_array = np.array(depth)
# Get the height and width of the depth image
height, width = undistorted_depth.shape

# Generate pixel coordinates
y, x = np.indices((height, width))
pixel_coords = np.stack((x, y), axis=-1).reshape(-1, 2)

# Flatten the depth image to create a 1D array of depth values
depth_values_flat = undistorted_depth.flatten()
instance_values_flat = undistorted_instances.flatten()


# Initialize an array to store 3D points

points_3d = []
valid_instances = []
for pixel_coord, depth, instance in zip(pixel_coords, depth_values_flat, instance_values_flat):
    # Ensure the depth value is valid
    if depth > 0:
        # Format the pixel coordinate for unproject (reshape to [2, 1])
        pixel_coord_reshaped = np.array([[pixel_coord[0]], [pixel_coord[1]]], dtype=np.float64)
    
        # Unproject the pixel to get the direction vector (ray)
        direction_vector = device.unproject(pixel_coord_reshaped)
        
        if direction_vector is not None:
            # Replace the z-value of the direction vector with the depth value
            # Assuming the direction vector is normalized
            direction_vector_normalized = direction_vector / np.linalg.norm(direction_vector)
            point_3d = direction_vector_normalized * depth
            
            # Append the computed 3D point and the corresponding instance
            points_3d.append(point_3d.flatten())
            valid_instances.append(instance)

# Convert the list of 3D points to a numpy array
points_3d_array = np.array(points_3d)
points_instances = np.array(valid_instances)`

**Comment by thucz** [comment]
How should I change the camera extrinsics after the rotation?
