### ISSUE TITLE
How  to get textured 3D obj 

### ISSUE THREAD

**Issue by raoqiang** [facebookresearch/projectaria_tools#110]
Thansks for the realease the dataset, how can we get the textured 3D obj files which we can use for render for multi-camera rgb and depths

**Comment by SeaOtocinclus** [comment]
Hello @raoqiang , can you elaborate about which dataset you are commenting on?

**Comment by SeaOtocinclus** [comment]
@raoqiang Closing due to no feedback, feel free to reopen when you add more details to your questions. Thank you

**Comment by nisarg-ujjainkar** [comment]
@SeaOtocinclus what about the Synthetic environment dataset? I could find the ply meshes but could not find the texture maps/materials. Where can I find those? Are there other datasets that come with assets that can be rendered?
