### ISSUE TITLE
alternative method for get_gaze_vector_reprojection

### ISSUE THREAD

**Issue by VJWQ** [facebookresearch/projectaria_tools#111]
Hi, thank you for the great project! 

I'm trying to project a 3d gaze on the egocentric image plane, however found that the provided code example can only use the built-in function `get_gaze_vector_reprojection` to project the pixel location on a 90-deg-rotated rgb image. Such a setting is quite constricted (two different sets of 2880x2880  or 1408x1408 calibration params are sealed in vrs/noimagestreams vrs) which is quite hard to fatch. **_I want to project a predicted 3d-gaze ray (composed by 2 (x,y,z) numbers) to a down-sampled 224x224 egocentric rgb frame_**. Since the fisheye camera doesn't have a linear conversion between pixel scales on different resolutions, I didn't find a direct solution to do this, can you share the script/pointers as an alternative to the built-in function? Thank you.

**Comment by SeaOtocinclus** [comment]
Hello @VJWQ 
We are recommending to stick to the original function to avoid having local implementation that would not match calibration of the device.

We are advising you to stick to using the function as it is (with the native calibration) and then downscale the projected point to match your target resolution image: this is what we are doing in the MPS_VIEWER https://github.com/facebookresearch/projectaria_tools/blob/6039d8ba1791e1a5a1acf3e5a802082b2ac5eda3/projectaria_tools/utils/viewer_mps.py#L286

FYI: the `get_gaze_vector_reprojection` source code can be found here https://github.com/facebookresearch/projectaria_tools/blob/6039d8ba1791e1a5a1acf3e5a802082b2ac5eda3/projectaria_tools/core/mps/utils.py#L131

**Comment by SeaOtocinclus** [comment]
@VJWQ  any additional feedback?
Please close the issue if you have the required information, else feel free to ask more questions.

**Comment by SeaOtocinclus** [comment]
Closing due to lack of feedback, feel free to reopen if needed.
