### ISSUE TITLE
Pickling binded classes

### ISSUE THREAD

**Issue by VladimirYugay** [facebookresearch/projectaria_tools#113]
Hey there,

I want to read data in a multiprocess setting. However, for many of the binded classes, there are no pickling methods. For example, for `AriaDigitalTwinDataProvider`. If I use it as is (assign it as a property to class which exists in a separate process), I get:

`TypeError: cannot pickle '_adt_pybinds.AriaDigitalTwinDataProvider' object`.

I tried patching it with:

```
class AriaDigitalTwinDataProviderWrapper(AriaDigitalTwinDataProvider):

    def __getstate__(self):
        return deepcopy(self.__dict__)

    def __setstate__(self, state):
        self.__dict__.update(state)


class AriaDigitalTwinDataPathsProviderWrapper(AriaDigitalTwinDataPathsProvider):

    def __getstate__(self):
        return deepcopy(self.__dict__)

    def __setstate__(self, state):
        self.__dict__.update(state)

```

however, it doesn't work. To test it I run `gt_provider.get_start_time_ns()`, then pickle, unpickle, and then run `gt_provider.get_start_time_ns()` and it gives me a wrong result. Moreover, accessing data from the unpickled object crashes without any messages (I assume seg fault). I guess that some of the dependencies of these classes also don't know how to pickle themselves? 

Is there a nice way to overcome this? Potentially, I could preprocess the data offline in a format I need and re-use it in a multiprocess setting but I want to avoid it and use the tools out-of-the-box.

**Comment by nickcharron** [comment]
Hi @VladimirYugay, thanks for your question. We currently have no plans to support pickling for our classes in projectaria_tools, or in ADT specifically. If you would like, we can document this as a feature request to consider in future releases. Alternatively, you can try to implement this feature yourself and even contribute the feature back to the repo via PR. Here is the documentation to help you get started: https://pybind11.readthedocs.io/en/stable/advanced/classes.html#pickling-support

**Comment by nickcharron** [comment]
Hi @VladimirYugay, I'm going to close this task but please re-open if you have any further questions or comments. Thanks!
