### ISSUE TITLE
Helper function to align SLAM outputs with device sensors

### ISSUE THREAD

**Issue by kaufManu** [facebookresearch/projectaria_tools#120]
I would like to temporally re-align the SLAM outputs with a sensor stream. For instance, assume I resampled the right IMU to 60 Hz and would like this to be the "master timeline", i.e. for every timestamp in the IMU signal, I'd like to find the corresponding trajectory point. For now I wrote my own function that loads the `tracking_timestamp_us` from the `closed_loop_trajectory.csv` file, then iterates through every available IMU timestamp and finds the closest "SLAM timestamp". This seems to work fine, but I'm unsure whether I'm not considering some edge cases and whether my alignment gives me the highest accuracy. In my tests so far there can be up to 0.5 milliseconds of misalignment, which is okay for now for my application, but is that in the range we would expect? I was wondering if you had any utility function that takes care of this alignment? Or may be there's an easier way to achieve the same thing that I'm currently not thinking of?

**Comment by kaufManu** [comment]
I was totally unaware of the `core.mps` utils, so apologies for the spam. It seems that the [`get_nearest_pose`](https://github.com/facebookresearch/projectaria_tools/blob/4c5108b2007b93f0274933320d740b4cacb16418/projectaria_tools/core/mps/utils.py#L68) is doing exactly what I want, right?

**Comment by SeaOtocinclus** [comment]
Yes `get_nearest_pose` is a candidate for you to use (see here the doc related to MPS)
Either in Python:
https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/core_code_snippets/mps#open-loopclosed-loop-trajectory

Or via our pybinding  -> mpsdataprovider aka. `get_closed_loop_pose` https://github.com/facebookresearch/projectaria_tools/blob/main/core/python/MpsPyBind.h#L592

**Comment by kaufManu** [comment]
Great, thanks for the pointers!
