### ISSUE TITLE
Will projectaria-client-sdk be open-sourced like this one?

### ISSUE THREAD

**Issue by luffy-yu** [facebookresearch/projectaria_tools#128]
This issue seems somewhat irrelevant.

I have compiled `projectaria_tools 1.5.4` on Windows 11 with VS 2019. 

The compiling was not easy, but it worked at least.

I am wondering if `projectaria-client-sdk` will be open-sourced or partially open-sourced.

I have looked into the Linux pypi package and found some `*.so` files.

```
libomp.so
libsdk_core.so
sdk.cpython-312-x86_64-linux-gnu.so
```

They seem confidential, but other Python files are fine.

Is it possible to provide these precompiled DLL libraries or the `*.whl` files for Windows?

Thanks,

**Comment by SeaOtocinclus** [comment]
Hello @luffy-yu , thank you for your question.

We don't have plan to release the projectaria-client-sdk as opensource, but as you saw we are improving the compatibility of our software eco-system with windows (see [Release notes](https://github.com/facebookresearch/projectaria_tools/releases/tag/1.5.4)).

Thank you for confirming also that you were able to compile projectaria_tools on windows.
If you are using Pixi, testing and compiling is getting very easy (same instruction for all your platforms):
```
# 1. Install Pixi -> see https://prefix.dev/
# 2. Compile and use your projectaria_tools flavor (C++ and or Python)

# C++ compilation + unit test run with Pixi package manager
pixi run run_c
# Python compilation + unit test run with Pixi package manager
pixi run run_python
```

**Comment by luffy-yu** [comment]
> Hello @luffy-yu , thank you for your question.
> 
> We don't have plan to release the projectaria-client-sdk as opensource, but as you saw we are improving the compatibility of our software eco-system with windows (see [Release notes](https://github.com/facebookresearch/projectaria_tools/releases/tag/1.5.4)).
> 
> Thank you for confirming also that you were able to compile projectaria_tools on windows. If you are using Pixi, testing and compiling is getting very easy (same instruction for all your platforms):
> 
> ```
> # 1. Install Pixi -> see https://prefix.dev/
> # 2. Compile and use your projectaria_tools flavor (C++ and or Python)
> 
> # C++ compilation + unit test run with Pixi package manager
> pixi run run_c
> # Python compilation + unit test run with Pixi package manager
> pixi run run_python
> ```

Thank you for your reply!

Actually, I compiled it using Anaconda, VCPKG, and VS 2019, not pixi. 

Pixi is new to me and I didn't try it out yet.

**Comment by SeaOtocinclus** [comment]
Thank you for sharing the toolchain you used.

- You should give a try to pixi (it can work to define your environment for python, C++ and other languages) and define tasks to enable you audience easy access to your resources (binaries, notebooks, ...)

**Comment by luffy-yu** [comment]
> Thank you for sharing the toolchain you used.
> 
> * You should give a try to pixi (it can work to define your environment for python, C++ and other languages) and define tasks to enable you audience easy access to your resources (binaries, notebooks, ...)

Sounds great! I will try.

I found that it seems that the latest client SDK on PyPI ([projectaria-client-sdk1.1.0](https://pypi.org/project/projectaria-client-sdk/)) only supports `projectaria-tools==1.5.2a1` not the latest 1.5.4 here.

BTW, when will the ProjectAria Client SDK support Windows?

**Comment by SeaOtocinclus** [comment]
Thank you for reporting that,
While waiting for the latest version to be built, you should be able to update the SDK to use the last version of projectaria_tools manually by doing:
```
pip install projectaria-client-sdk
pip install projectaria-tools --upgrade
```

**Comment by luffy-yu** [comment]
> Thank you for reporting that, While waiting for the latest version to be built, you should be able to update the SDK to use the last version of projectaria_tools manually by doing:
> 
> ```
> pip install projectaria-client-sdk
> pip install projectaria-tools --upgrade
> ```

You are welcome!

Since ProjectAria Tools just had Windows support, I assume there will be Windows-supported ProjectAria Client SDK soon or later. 

I will explore further and wait for it.
