### ISSUE TITLE
Baseline of Project ASE Scene Reconstruction Challenge

### ISSUE THREAD

**Issue by ZheningHuang** [facebookresearch/projectaria_tools#133]
Hi,

I understand that the challenge has closed, but I was wondering if the code for the baseline of Host_80188_Team (ASE Baseline) is available for us to test, or if it is a closed-source baseline.

<img width="1152" alt="image" src="https://github.com/user-attachments/assets/e503e2de-d81e-4cfe-96f5-65b8f3789d28">

Best regards,
Zhening

**Comment by suvampatra** [comment]
Hi @ZheningHuang, thanks for your interest. 

The code is closed-source ATM. The paper for the baseline method is available at https://arxiv.org/abs/2403.13064. 

However, please subscribe to email updates at https://www.projectaria.com and we will notify if there are any updates about the above.

I am closing this issue with this, but feel free to re-open it if you have any other queries.
