### ISSUE TITLE
segmentations_with_skeleton.vrs not in the download links?

### ISSUE THREAD

**Issue by georgegu1997** [facebookresearch/projectaria_tools#142]
In the newest dataset download links for the ADT dataset, seems the `segmentations_with_skeleton.vrs` files have become not available anymore, and only the `segmentations.vrs` can be downloaded. Yet they are still referenced [here](https://github.com/facebookresearch/projectaria_tools/blob/main/projects/AriaDigitalTwinDatasetTools/data_provider/AriaDigitalTwinDataPathsProvider.h#L79) and [here](https://facebookresearch.github.io/projectaria_tools/docs/open_datasets/aria_digital_twin_dataset/data_loader#:~:text=with%20skeleton%20occlusion-,data_paths_with_skeleton_occlusion%20%3D%20paths_provider.get_datapaths(True),-AriaDigitalTwinDataProvider%E2%80%8B). 

Is this a permanent removal for that part of ground truth segmentation data?

**Comment by nickcharron** [comment]
Hi @georgegu1997 , thanks for bringing this to our attention. It looks like these files were missed on the new release, I will work on this asap and let you know when the files are available again.

**Comment by nickcharron** [comment]
Hi @georgegu1997, this issue has been resolved, you should now be able to download he segmentations_with_skeleton.vrs and depth_with_skeletons.vrs. Make sure you re-download the updated download links file from projectaria.com first. Thanks again for raising the issue.

Closing this task, but feel free to re-open if this isn't working for you or if you have any follow up questions!

**Comment by georgegu1997** [comment]
Thanks for the update! It now works on my end.
