### ISSUE TITLE
[ADT] questions regarding some sequences

### ISSUE THREAD

**Issue by SunghwanHong** [facebookresearch/projectaria_tools#149]
Hi, 

I noticed that I can not retrieve the depth and segmentation for some of the sequences.
For example, while I can retrieve the RGB images and pose for "Apartment_release_clean_seq131_M1292", segmentation and depth map are not available even though there is depth_images.vrs and segmentations.vrs in the folder I downloaded.

However, this does not occur with some of the other scenes, such as "Apartment_release_multiskeleton_party_seq101_M1292"

This is pretty weird to me since those vrs files are already in the adt folder but when I am to preprocess them for 3dgs, somehow some of the sequences can not retrieve the segmentation and depth results..

For example, https://github.com/facebookresearch/egolifter/blob/d177089a153831e4cd592fb09c8f86f8a63d398c/scripts/process_adt_3dgs.py#L302, even though I have the segmentation or depth file available, I can not somehow retrieve the corresponding depth or segmentation except for the rgb. 

Do you have any idea what's going on with this?

**Comment by nickcharron** [comment]
Hi @SunghwanHong, thanks for submitting an issue. Looking into Apartment_release_clean_seq131_M1292, the depth and segmentation data does look fine to me when using our standard visualization tool. You can see the pre-rendered video on our explorer for this sequence which shows the depth and segmentation images: [see here](https://explorer.projectaria.com/adt/Apartment_release_clean_seq131_M1292?q=%22sequence_uid+%3D%3D+Apartment_release_clean_seq131_M1292%22&st=%220%22). 

Is it possible there is something wrong in your code when trying to access the data? A common problem I see is that the raw vrs file starts recording a little while before ground truth data gets generated so you have to ignore those images. We explain this in the  [ADT quickstart tutorial](https://colab.research.google.com/github/facebookresearch/projectaria_tools/blob/1.5.5/projects/AriaDigitalTwinDatasetTools/examples/adt_quickstart_tutorial.ipynb), and explain that you should use get_start_time and get_end_time functions in the ADT data provider.  Please have a look and see if that's the issue.

**Comment by SunghwanHong** [comment]
Hi @nickcharron,

Thanks for the quick reply. It seems that https://github.com/facebookresearch/egolifter/issues/9#issuecomment-2460300816, the author of egolifter (ECCV'24) also experienced the same issue. 

What I'm doing in my code is simply following the tutorial:
 segmentation_with_dt = gt_provider.get_segmentation_image_by_timestamp_ns(timestamp_ns, stream_id)
depth_with_dt = gt_provider.get_depth_image_by_timestamp_ns(timestamp_ns, stream_id)

However, from those two lines, for some of the sequences such as Apartment_release_clean_seq131_M1292, even though I put the same stream_id and timestamp_ns used to retrieve an image like this : 
image_with_dt = gt_provider.get_aria_image_by_timestamp_ns(timestamp_ns, stream_id),
I somehow find these error messages :
![image](https://github.com/user-attachments/assets/f42575e9-14fb-45c3-afdb-f8ba340de8a2)

In the warning yes, it says to check the get_start_time_ns and get_end_time_ns. However, in the tutorial, it simply skips the iteration within the for loop by 'continue', so I'm guessing it is not a right solution? 

Thank you so much for your time!

**Comment by nickcharron** [comment]
@SunghwanHong yes that definitely looks like the issue. I think we should ask the author of egolifter to add the get_start_time and get_end_time checks in his code

**Comment by SunghwanHong** [comment]
Right! 

But then if I add get_start_time and get_end_time, wouldn't it make the whole timestamps to be skipped?

**Comment by nickcharron** [comment]
@SunghwanHong you should use get_start_time and get_end_time to get the time range of valid data, then not process images that are outside of that time range

**Comment by SunghwanHong** [comment]
I guess what you suggested is to do something like this ?
![image](https://github.com/user-attachments/assets/00c2a9c2-da3a-4f92-9edd-c11e9ef48a34)

However, this also gives the same results though!

**Comment by nickcharron** [comment]
Yeah that's what I'm suggesting. Can you share the error you're getting after adding that?

Also, can you try to run our c++ visualizer to see if your data is correct? See instructions here: https://facebookresearch.github.io/projectaria_tools/docs/open_datasets/aria_digital_twin_dataset/visualizers#c-visualizer

**Comment by SunghwanHong** [comment]
![image](https://github.com/user-attachments/assets/7ba204b8-9dc2-44ca-b455-8c1bb6e0d554)

I will try the visualizer!

**Comment by georgegu1997** [comment]
Thanks for the discussion! In EgoLifter, we [skipped the frames without GT](https://github.com/facebookresearch/egolifter/blob/d177089a153831e4cd592fb09c8f86f8a63d398c/scripts/process_adt_3dgs.py#L302), which should lead to the same set of processed frames as using `get_start_time` and `get_end_time`.

**Comment by nickcharron** [comment]
@georgegu1997 thanks for your reply. I see the logic behind your solution. One potential issue with just checking the dt is that there is actually a slight variable timing misalignment between raw aria images and depth/segmentation images. Please take a look at my comment here: https://github.com/facebookresearch/projectaria_tools/issues/81#issuecomment-2105300757. Unfortunately, this isn't something we can fix in the data itself.

@SunghwanHong I just downloaded the sequence you are working with and ran the visualizer and the data looks fine. So it's likely either an issue with your downloaded data, or the way you're using the data.

**Comment by SunghwanHong** [comment]
Thanks for checking the visualizer! I'm about to re-download the sequence, but I'm not sure what could've been wrong in using the segmentation and depth. Since what I only did was simply running the egolifter's code i attached above, and what it does is simply taking the exact same timestamp and stream_id as inputs, gt_provider trying to retrieve the seg map or depth map. I really have no clue since the timestamp and stream_Id are unchanged compared to when i'm retrieving rgb. Would it be possible if you confirm that the timestamp 13860384112587 for sequence Apartment_release_clean_seq131_M1292 works to retrieve rgb, depth and seg map?

**Comment by georgegu1997** [comment]
Hi @SunghwanHong, I just checked and I think this is what happened. 

EgoLifter by default uses `segmentation_with_skeleton.vrs` by setting `skeleton_flag=True` in [this line](https://github.com/facebookresearch/egolifter/blob/main/scripts/process_adt_3dgs.py#L173). 
However, somehow downloading `Apartment_release_clean_seq131_M1292` only gives `segmentation.vrs` but not the `segmentation_with_skeleton.vrs`. (As name suggests, `segmentation.vrs` only gives you segmentation masks of objects but not the humans in the sequences. ) This is why even though `13860384112587` is within the start and end time, it still gives no segmentation. If you change `skeleton_flag=True` to `skeleton_flag=False`, you should be able to run the code. Yet this does not give you human segmentation masks. 

I thought this issue was fixed by #142 but seems it's not fixed for all the sequences. I can confirm that `Apartment_release_clean_seq131_M1292` does not download `segmentation_with_skeleton.vrs` but other sequences like `Apartment_release_multiskeleton_party_seq122_71292` does. 

@nickcharron Is the `segmentation_with_skeleton.vrs` only available for some sequences, or is this still a downloading/sourcing issue?

**Comment by nickcharron** [comment]
Hi @georgegu1997, thanks for looking into this. Only some sequences have skeleton data (see [docs](https://facebookresearch.github.io/projectaria_tools/docs/open_datasets/aria_digital_twin_dataset/data_format#skeleton-data-and-availability)), so if you're always looking for segmentation_with_skeleton.vrs then yes some sequences won't load the segmentations. I suggest you check the metadata.json in each sequence, there is a 'num_skeletons' key which you can check before trying to load the segmentation data. 

@SunghwanHong please let us know if this solves your issue, if so we can close this task

**Comment by SunghwanHong** [comment]
Thank you @nickcharron  and @georgegu1997! Now my issue is solved, I'm closing this issue.
