### ISSUE TITLE
Cannot find Mask Generation Script in DTC Tooling

### ISSUE THREAD

**Issue by puhuajiang** [facebookresearch/projectaria_tools#150]
Thank you for your amazing project !
I cannot find "Mask Generation Script" in DTC Tooling and will this be released soon?

**Comment by SeaOtocinclus** [comment]
Closing and please follow #154

**Comment by SeaOtocinclus** [comment]
Tooling is now available Tooling is now available https://github.com/facebookresearch/DigitalTwinCatalogue
