### ISSUE TITLE
the camera intrinisics

### ISSUE THREAD

**Issue by AnarchistKnight** [facebookresearch/projectaria_tools#151]
Good day, may I ask the camera intrinsic and camera distortion parameters of AriaSyntheticEnvironment dataset?

**Comment by SeaOtocinclus** [comment]
You can retrieve them using the vrs_data_provider interface.
See the documentation [here](https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/core_code_snippets/calibration)

**Comment by AnarchistKnight** [comment]
> You can retrieve them using the vrs_data_provider interface. See the documentation [here](https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/core_code_snippets/calibration)

Thank you for reply. It would take me a while to dig into how to calibrate the rgb images provided in AriaSyntheticEnvironment dataset. I would also be happy if you don't mind tell me how to directly do this. Have a good day!
