### ISSUE TITLE
Aria Client SDK Streaming Subscription ThreadPoolExecutor Error and White Screens

### ISSUE THREAD

**Issue by JonOuyang** [facebookresearch/projectaria_tools#152]
Hi,

I'm trying to get the aria glasses to livestream and display onto my desktop using the USB connection (we tried with wifi as well to no avail)

Specs:
OS: Linux (Ubuntu 24.04)
Python: 3.12.4
projectaria-tools: 1.5.2a1

We have:
- cloned the codebase as instructed under installation guide
- installed python package installation as instructed
- installed aria studio as instructed
- followed all of the  instructions in setup guide under aria client sdk

We attempted installation with both conda and venv, and faced no issues during installation.

When we attempt to run the streaming command, we face no issues running the 
`aria streaming start --interface usb --use-ephemeral-certs`
command, and the little white light on the glasses turns on indicating its starting to stream.

We then run into our issues when using the
`python -m streaming_subscribe`
command. The GUI that appears is completely white except for a small rectangular black rectangle on BOTH RGB and SLAM panels (see screenshot below)

![image](https://github.com/user-attachments/assets/dd44f41f-cb1b-437a-8704-84ad15e8a7ba)

We also noticed that in the terminal we get the following:

/home/u-ril/projectaria_client_sdk_samples/streaming_subscribe.py:18: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import aria.sdk as aria
Start listening to image data
WARNING: Logging before InitGoogleLogging() is written to STDERR
E1108 16:45:12.998821 1306527424 Executor.cpp:31] ThreadPoolExecutor: func threw unhandled pybind11::cast_error: Unable to convert call argument to Python object (#define PYBIND11_DETAILED_ERROR_MESSAGES or compile in debug mode for details)

There is a deprecation warning for pkg_resources and a ThreadPoolExecutor error. 

Do you have any idea what might be going wrong? Did we forget to install something somewhere down the line? Please let us know your thoughts. Thanks

**Comment by JonOuyang** [comment]
We actually resolved this issue by downgrading python to 3.9.20!

**Comment by SeaOtocinclus** [comment]
Closing the issue since you found a solution, thank you for sharing the solution you found
