### ISSUE TITLE
No DTC Tooling scripts.

### ISSUE THREAD

**Issue by zhejia01** [facebookresearch/projectaria_tools#154]
It seems that there is no scripts in DTC Tooling including： 
Rerun Visualizer Script
Mask Generation Script

**Comment by SeaOtocinclus** [comment]
FYI: Related to #150

**Comment by zhejia01** [comment]
It seems that there is no reply in #150 . Would you provide some suggestions?

**Comment by SeaOtocinclus** [comment]
Tooling is now available https://github.com/facebookresearch/DigitalTwinCatalogue
