### ISSUE TITLE
matching different frames in one sequence

### ISSUE THREAD

**Issue by AnarchistKnight** [facebookresearch/projectaria_tools#155]
Good day.

I tried to reconstruct a ASE scene and failed.  I guess I might miss something when computing the camera pose matrix or when converting depth to z. My workflow is as follows:
1. Scene 8 from ASE dataset is used.
2. The rgb and depth images are rectified, as example shown in projectaria_tools/core/examples/dataprovider_quickstart_tutorial.ipynb. I finally got images of 512x512 size and they look right. The left is the original and the right is the undistorted.

![image](https://github.com/user-attachments/assets/2e7e89d6-e8b3-4c80-bf1a-e6c28255ef21)

3. Depth is converted to z using the function below. 
~~~
CORRECTION_PARAM = 1000.0

# fx = 150, fy = 150, cx = 256, cy = 256
def convert_depth_to_z(fx, fy, cx, cy, depth_image_path):
    depth_image = cv2.imread(depth_image_path, cv2.IMREAD_UNCHANGED)

    constant_x = 1 / fx
    constant_y = 1 / fy

    vs = np.array([(v - cx) * constant_x for v in range(0, depth_image.shape[1])])
    us = np.array([(u - cy) * constant_y for u in range(0, depth_image.shape[0])])

    z_image = np.square(depth_image / CORRECTION_PARAM)
    scale = 1 + np.square(vs[np.newaxis, :]) + np.square(us[:, np.newaxis])
    z_image = np.sqrt(z_image / scale) * CORRECTION_PARAM
    return z_image.astype(np.uint16)
~~~
4. The camera_to_world matrix is computed using this function
~~~
from scipy.spatial.transform import Rotation

def c2w(tx, ty, tz, qx, qy, qz, qw):
    quaternion = [qx, qy, qz, qw]
    rotation = Rotation.from_quat(quaternion)
    rotation_matrix = rotation.as_matrix()
    camera_pose_matrix = to_homo(rotation_matrix)
    camera_pose_matrix[0][3] = tx
    camera_pose_matrix[1][3] = ty
    camera_pose_matrix[2][3] = tz
    return camera_pose_matrix
~~~
5. I used open3d to try to reconstruct the scene. The result for single frame at 0 looks correct.

![image](https://github.com/user-attachments/assets/9821a8d6-55a8-495a-bf97-b12deeb07689)

6. The result for single frame at 18 looks wrong. The camera trajectory goes into the wall.

![image](https://github.com/user-attachments/assets/79fe9813-bc07-48df-84f3-74f76e401911)

7. The reconstruction for multple frames 82-92 looks a bit corrupted, difference frames do not match to each other.

![image](https://github.com/user-attachments/assets/1f0c78be-db57-4eed-b829-72bfbcb7b68a)

8. The reconstruction for the whole sequence looks a mess.

![image](https://github.com/user-attachments/assets/da2e5348-dcfa-4b01-a5f8-fe4cbd6edd02)

**Comment by AnarchistKnight** [comment]
Solved. I notice code ![here](https://github.com/facebookresearch/projectaria_tools/blob/main/core/examples/mps_quickstart_tutorial.ipynb)

~~~
def build_camera_frustum(transform_world_device):
    points = (
        np.array(
            [[0, 0, 0], [0.5, 0.5, 1], [-0.5, 0.5, 1], [-0.5, -0.5, 1], [0.5, -0.5, 1]]
        )
        * 0.6
    )
    transform_world_rgb = transform_world_device @ T_device_RGB
    points_transformed = transform_world_rgb @ points.transpose()
    return go.Mesh3d(
        x=points_transformed[0, :],
        y=points_transformed[1, :],
        z=points_transformed[2, :],
        i=[0, 0, 0, 0, 1, 1],
        j=[1, 2, 3, 4, 2, 3],
        k=[2, 3, 4, 1, 3, 4],
        showscale=False,
        visible=False,
        colorscale="jet",
        intensity=points[:, 2],
        opacity=1.0,
        hoverinfo="none",
    )
~~~

**Comment by SeaOtocinclus** [comment]
@AnarchistKnight Happy to hear that you found a solution to your problem and thank you for sharing your code, so anyone can rely on your solution if they have the same problem

**Comment by Rock-100** [comment]
@AnarchistKnight Thanks for kindly sharing information! Could you please share your full script or the code for distortion? I am also working on this but have been getting poor results. I suspect it might be because I used a different method for undistortion (https://github.com/facebookresearch/projectaria_tools/issues/11). Thank you very much!

**Comment by AnarchistKnight** [comment]
> @AnarchistKnight Thanks for kindly sharing information! Could you please share your full script or the code for undistortion? I am also working on this but have been getting poor results. I suspect it might be because I used a different method for undistortion (#11). Thank you very much!

search "undistort an image" in https://github.com/facebookresearch/projectaria_tools/blob/main/core/examples/dataprovider_quickstart_tutorial.ipynb

**Comment by AnarchistKnight** [comment]
> @AnarchistKnight Thanks for kindly sharing information! Could you please share your full script or the code for undistortion? I am also working on this but have been getting poor results. I suspect it might be because I used a different method for undistortion (#11). Thank you very much!

solved?

**Comment by Rock-100** [comment]
@AnarchistKnight Yes, thank you!

**Comment by Wang-Wentao** [comment]
Hello, Thansk for yout sharing. But I found the rgb & depth is 704*704, why you got the undistored image is  512*512, and how to process the depth (704*704) to align the 512*512 rgb to got the 3d cloud points. 
I would be grateful if you could provide the complete code.
