### ISSUE TITLE
[ADT] how to convert the point in camera coordinates to world coordinates?

### ISSUE THREAD

**Issue by yaojin17** [facebookresearch/projectaria_tools#159]
Hi there, thank you for your amazing project! I am using the Aria Digital Twin dataset, and I want to know how to get the extrinsics of the camera-rgb for each timestamp. For example, in this folder of a video: `projectaria_tools_adt_data/Apartment_release_clean_seq131_M1292/mps/slam/`, there are two files: `closed_loop_trajectory.csv` and `online_calibration.jsonl`. Which one contains the extrinsics of the camera-rgb? Could you also provide a small code snippet for converting a 3D point in camera coordinates to world coordinates, or share a link to a tutorial? Thanks a lot!

**Comment by nickcharron** [comment]
Hi @yaojin17, we actually have a tutorial that shows how to take depth images and convert them to a pointcloud in the world frame. It also shows how to use the RGB images to color that pointcloud. Please take a look at the tutorial here: https://facebookresearch.github.io/projectaria_tools/docs/open_datasets/aria_digital_twin_dataset/advanced_tutorials/depth_maps_to_pointcloud

This shows how to get the camera extrinsics as well as the devices poses all using our AriaDigitalTwinDatasetProvider, so I hope this will answer all your questions.

**Comment by yaojin17** [comment]
Thanks for your light-speed answer. That's awesome! I think this could solve my problem. Thanks!
