### ISSUE TITLE
ASE camera calibration

### ISSUE THREAD

**Issue by PavanMantripragada** [facebookresearch/projectaria_tools#162]
This code gives a single set of camera instrinsics, how can I get scene specific parameters? Does entire ASE have a single intrinsics.
```
from projectaria_tools.projects import ase
device = ase.get_ase_rgb_calibration()
T_device_from_camera = self.device.get_transform_device_camera().to_matrix()
```

**Comment by suvampatra** [comment]
Yes indeed, the ASE scenes are simulated with single set of intrinsics, which doesnt change over scenes, Hope that answers your question.
