### ISSUE TITLE
AttributeError: '_core_pybinds.sophus.SE3d' object has no attribute 'to_matrix'

### ISSUE THREAD

**Issue by sguttikon** [facebookresearch/projectaria_tools#19]
Hello, I am facing no attribute 'to_matrix' when running example 'AriaDigitalTwinDatasetTools/examples/adt_quickstart_tutorial.ipynb'

**Comment by AlbertoJaenal** [comment]
Hi, @sguttikon!
Indeed, that attribute does not exist. You should access to the transform using `.matrix()` instead of `.to_matrix()`.
Hope it works

**Comment by SeaOtocinclus** [comment]
This is known issue, we are updating our Sophus pybind for our coming release (v1.2.0)
Temporary solution:
- Revert to the previous version of the file (similar to the solution proposed by @AlbertoJaenal 
- You can use the projectaria_tools==1.2.0rc1
- Or compile projectaria_tools bindings yourself

Sorry for the inconvenience.

**Comment by SeaOtocinclus** [comment]
@sguttikon We have now release v1.2.0 -> https://github.com/facebookresearch/projectaria_tools/releases/tag/1.2.0
Python notebooks and `pip install projectaria-tools` are now matching!

Closing for now, feel free to re-open if you encounter any issue.
