### ISSUE TITLE
Question on scenes filtering

### ISSUE THREAD

**Issue by VladimirYugay** [facebookresearch/projectaria_tools#2]
Hey there! Thanks for your work. 

I have a question about the Aria Digital Twin dataset. 

From the 200 sequences, is there a quick way to filter them?

For example, I want to get the following:

1. Sequences without any humans in the view
2. Sequences without moving objects

**Comment by nickcharron** [comment]
Hi Vladimir! Thanks for the question. 

We provide a metadata file you can download using the adt_benchmark_dataset_downloader (which comes with projectaria-tools python package) which describes the content of each sequence. You can use this to filter the sequences for certain criteria. We also provide an [example script](https://github.com/facebookresearch/projectaria_tools/blob/main/projects/AriaDigitalTwinDatasetTools/scripts/aria_digital_twin_dataset_searcher.py) to show how to filter the dataset for specific content. This example shows how to filter for sequences with skeleton, without skeleton, with multiple people, with single person, and filter by scene. See [this section](https://facebookresearch.github.io/projectaria_tools/docs/open_datasets/aria_digital_twin_dataset/dataset_download#select-specific-sequences) of the wiki that describes how to do this. 

To filter for the specific content you mention:
1. If you filter for single user datasets (i.e., is_multi_person == false in metadata json), then there won't be any humans in the view other than the person wearing the Aria device
2. Unfortunately the metadata file doesn't contain information on which objects are in each sequence. However, I believe almost all datasets have some moving objects. If you want to find out more about the types of objects in each dataset, you will have to download the datasets and for each dataset: create a dataset loader, extract all instance Ids, extract the instance info for each instance, and then you can check the motion_type. Let me know if you need some more help with this!

**Comment by VladimirYugay** [comment]
Thanks for your response. 

Are there at least some sequences passing through the exact same unchanged environment?

**Comment by SeaOtocinclus** [comment]
@VladimirYugay Do you mind closing the issue if you have all the answers you need?
If you still have some questions unanswered, please elaborate to help us provide better guidance. Thank you.
