### ISSUE TITLE
[ASE] Release of object model IDs and object poses?

### ISSUE THREAD

**Issue by angshine** [facebookresearch/projectaria_tools#21]
Hi, thanks for the excellent work and for releasing the ADT & ASE datasets! 

I was wondering if it would be possible to also release the ABO object model IDs and the object poses used in each ASE scene for constructing the mesh of each scene. This would be very helpful for evaluating reconstruction methods on the ASE dataset.

**Comment by suvampatra** [comment]
Hey @angshine, Thanks for using  ADT & ASE datasets. For ASE, at the moment we have additionally provided the semantic labels for each of the scenes as requested by https://github.com/facebookresearch/projectaria_tools/issues/1. The original intention for this version of the release is mainly indoor floorplan reconstruction.

We intend to have a future version, which will have more information including object poses/ ABO model ids etc. 

But at the moment, we intend to stick with the semantic labels + instance segmentation images

**Comment by angshine** [comment]
Thanks! Looking forward to the future version!
