### ISSUE TITLE
Inconsistency in reprojection

### ISSUE THREAD

**Issue by Davidyao99** [facebookresearch/projectaria_tools#22]
I am trying to undistort the depth image, but I realized that undistorting the entire depth image using `calibration.distort_by_calibration` compared to doing it pixel by pixel using `src_calib.unproject_no_checks` and `dst_calib.project` gives very different results. 

After visualizing the 3D reconstruction of the point clouds, it seems like undistorting using `calibration.distort_by_calibration` leads to issues. However, undistorting every pixel point by point is very inefficient. Is there a way to perform the same unprojection as `src_calib.unproject_no_checks` and `dst_calib.project` but on batches of points for better speed up?

**Comment by SeaOtocinclus** [comment]
If you use `distort_by_calibration` on depth data you need to conver the array to double.
See [here](https://github.com/facebookresearch/projectaria_tools/issues/11) and [there](https://github.com/facebookresearch/projectaria_tools/issues/13#issuecomment-1688942880)

**Comment by Davidyao99** [comment]
@SeaOtocinclus I see, I am using float32 right now. Perhaps using float64 will account for the difference!

**Comment by Davidyao99** [comment]
For a more concrete example of this issue, I wrote some code showing this difference.

`img_timestamps_ns = gt_provider.get_aria_device_capture_timestamps_ns(stream_id)
depth_with_dt = gt_provider.get_depth_image_by_timestamp_ns(img_timestamps_ns[712], stream_id)

# check if the result is valid
if not depth_with_dt.is_valid():
    print("depth map not valid for input timestamp!")
print("groundtruth_time - query_time = ", depth_with_dt.dt_ns(), "ns")

depth_image = depth_with_dt.data().to_numpy_array().astype(np.float32)
sensor_name = gt_provider.raw_data_provider_ptr().get_label_from_stream_id(stream_id)
device_calib = gt_provider.raw_data_provider_ptr().get_device_calibration()
src_calib = device_calib.get_camera_calib(sensor_name)
dst_calib = calibration.get_linear_camera_calibration(1220, 1220, 400, sensor_name)

map = np.zeros((1220, 1220, 2), dtype=np.int32)

for x in range(0,1220):
    for y in range(0,1220):
        point = np.array([x, y])
        unprojected_point_ray = dst_calib.unproject_no_checks(point)
        rect_point = src_calib.project(unprojected_point_ray)

        if rect_point is None:
            map[y][x] = np.array([-1, -1])
        else:
            map[y][x] = np.array([int(rect_point[0]), int(rect_point[1])])

rectified_image = calibration.distort_by_calibration(depth_image, dst_calib, src_calib)

undistorted_depth_image = np.zeros((1220, 1220))

for x in range(0,1220):
    for y in range(0,1220):
        mapping = map[y][x]
        if mapping[0] == -1:
            continue
        undistorted_depth_image[y][x] = depth_image[int(mapping[1])][int(mapping[0])]
    `
    
undistorted_depth_image is formed by projecting each pixel from destination calibration to original calibration and querying for the depth.

rectified_image is formed by projecting the entire depth image from original calibration to destination calibration.

![image](https://github.com/facebookresearch/projectaria_tools/assets/52120948/a28f5514-dd90-4ff0-9a70-48674bbff27d)

 This is the difference of the two images, with some edge misalignments. This might be due to rounding errors? I tried reprojecting the 3D pointcloud using these 2 different depth values. The one from rectified_image leads to strange floating point clouds in the middle of the space, while the one from undistorted_depth_image seems to form a nice 3D pointcloud. Any idea why this could be happening? Thanks!!

**Comment by Davidyao99** [comment]
I see, so calibration.distort_by_calibration projects each ray at the centre of each pixel (0.5, 0.5) for the top left most pixel, but in my own per-pixel implementation, I am projecting the ray at the top left corner of each pixel (0,0) for top left?

**Comment by SeaOtocinclus** [comment]
Yes I believe this is what is happening. You can try to add the pixel shift to your sampler
`map[y][x] = np.array([int(rect_point[0] + .5), int(rect_point[1] + .5)])` and see if images align or not

**Comment by Davidyao99** [comment]
I implemented your suggestion and it seems to remove some of the errors. However, there is still some error existing. This is the difference.

![image](https://github.com/facebookresearch/projectaria_tools/assets/52120948/39f97927-5a85-4e09-93d7-5c0012e634c8)

The mean of the absolute difference per pixel is 4mm.

**Comment by chpeng-fb** [comment]
@Davidyao99 Here is also the page where we specify the 2D image coordinates systems that introduced this 0.5 pixels shift
https://facebookresearch.github.io/projectaria_tools/docs/data_formats/coordinate_convention/2d_image_coordinate_system_convention

**Comment by chpeng-fb** [comment]
The underlying he c++ implementation in distort_by_calibration is here
https://github.com/facebookresearch/projectaria_tools/blob/52a6b3ab91b308670c24aa0ab087babf10672a41/core/calibration/utility/Distort.cpp#L26-L29

But 4mm error does seem like a numeric error between the python float32 and c++ double.
