### ISSUE TITLE
Aria trajectory and GT pose world coordinate system

### ISSUE THREAD

**Issue by cdforigua05** [facebookresearch/projectaria_tools#24]
Hi !,
I'm interested in using the aria trajectory, but I have a question regarding the world coordinate systems between the aria trajectory and the GT 3D body poses. I plot the aria trajectory against the "head" point, which differs significantly. The blue line is the head point, and the green one corresponds to the aria translation vector.

![image](https://github.com/facebookresearch/projectaria_tools/assets/66923636/001b80ca-e453-4963-8adf-91b2cdf38cca)

Is this behavior normal? 
I'm using the AriaDigitalTwinDataProvider to get the information as follows:
` gt_provider = AriaDigitalTwinDataProvider(data_paths)` 
` aria_trans = gt_provider.get_aria_3d_pose_by_timestamp_ns(timestamp).data().transform_scene_device.translation()` 
` head = skeleton.joints[4]`

I ensure the timestamps are between the range `gt_provider.get_end_time_ns()` and `gt_provider.get_start_time_ns()` to retrieve the GT. I'm assuming dimensions 0,1, and 2 correspond to x,y, and z, respectively. 

Is there any transformation I need to apply to locate GT body pose and aria trajectory in the same coordinate system?

Thank you so much for your help.

**Comment by nickcharron** [comment]
Hi @cdforigua05,

Your sample code looks fine to me. Both the Aria 3d poses and the skeleton joint positions are in the same reference frame so you shouldn't need anything more. Which dataset are you using? 

For most datasets, the Aria wearer is also the person wearing the bodysuit, but not for all datasets. We provide a file called: skeleton_aria_association.json which shows you which skeleton is associated with which Aria device. You can take a look at that to see that they are associated, or you can also access this information by checking the InstanceInfo for the skeleton and making sure the [associatedDeviceSerial](https://github.com/facebookresearch/projectaria_tools/blob/main/projects/AriaDigitalTwinDatasetTools/data_provider/AriaDigitalTwinDataTypes.h#L317) is the same as the trajectory you are plotting

**Comment by cdforigua05** [comment]
Hi @nickcharron , I'm using the ADT Dataset
Where can I find the skeleton_aria_association.json ? 
Thanks for your help

**Comment by nickcharron** [comment]
Sorry I meant which specific sequence are you using? You can find the skeleton_aria_association.json in the root directory of the subsequence you are using. See: https://facebookresearch.github.io/projectaria_tools/docs/open_datasets/aria_digital_twin_dataset/data_format

**Comment by cdforigua05** [comment]
I'm using the sequence Apartment_release_multiuser_cook_seq141. I just verified and it seems that the device match with the skeleton information

**Comment by nickcharron** [comment]
I took a look at that specific dataset, and it looks like the user wearing the bodysuit is not wearing the Aria. If you take a look at the skeleton_aria_association.json:

![image](https://github.com/facebookresearch/projectaria_tools/assets/19352517/52f914f6-e49b-4df0-862c-2f43c1f90bcd)

You can see that the Aria with serial 1WM103600M1292 has no associated skeleton, and the skeleton Skeleton_T has no associated Device serial

So what you're seeing in your plot is expected.

**Comment by cdforigua05** [comment]
You're right @nickcharron. In the other sequences the aria trajectory and the head match perfectly.

![image](https://github.com/facebookresearch/projectaria_tools/assets/66923636/0201e8bd-6499-4b3c-a828-766ecfb0e526)

Thank you so much for all the help. I'm closing the issue.
