### ISSUE TITLE
Incomplete Code Snippets in the Aria Project Tools Documentation

### ISSUE THREAD

**Issue by Sid2697** [facebookresearch/projectaria_tools#26]
Hello!

The code [here](https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/advanced_code_snippets/image_utilities) seems to have some missing components.

> from projectaria_tools.core import data_provider, calibration
> camera_label = "camera-slam-left"
> stream_id = provider.get_stream_id_from_label(camera_label)
> calib = provider.get_device_calibration().get_camera_calib(camera_name)
> pinhole = calibration.get_linear_camera_calibration(512, 512, 150)
> raw_image = provider.get_image_data_by_index(stream_id, 0)[0].to_numpy_array()
> undistorted_image = calibration.distort_by_calibration(raw_image, pinhole, calib)

1. `camera_name` is not defined here and I could not find it in the entire Project Aria Tools documentation.
2. `provider` is not defined. I assumed it is created by `dataprovider.create_vrs_data_provider` from [here](https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/advanced_code_snippets/plotting_sensor_data). However, this means that we need to load vrs file and re-extract the images to generate undistorted images.

I believe the above code snippet needs to be updates for the missing variables.

Also, Is it possible to undistort already extracted raw image (loaded using OpenCV) without creating the provider object?

**Comment by chpeng-fb** [comment]
Hi @Sid2697,

Thank you for the feedback! The code snippets need to be updated. 
`camera_name` here should actually be `camera_label`
`provider = data_provider.create_vrs_data_provider(vrsfile)`

For more specific examples, please refer to the notebook example code
https://github.com/facebookresearch/projectaria_tools/blob/main/core/examples/dataprovider_quickstart_tutorial.ipynb

The undistortion function needs to take in 3 variables. The image as numpy array, src and dst calibration. The src calibration for the original image needs to be created by loading the provider and getting the calibration. However, you can also get the calibration by this function `device_calibration_from_json_string` that loads the calibration of a device from a json string. https://github.com/facebookresearch/projectaria_tools/blob/main/core/python/DeviceCalibrationPyBind.h#L460-L476

The json string can be provided using command `vrs print-json file.vrs`, which you can find more details in this website
https://facebookresearch.github.io/vrs/docs/VrsCliTool/

Sorry for the inconvenience.

**Comment by Sid2697** [comment]
@chpeng-fb 

Thank you for your response!

> However, you can also get the calibration by this function device_calibration_from_json_string that loads the calibration of a device from a json string.

Here, is the `json string` the one that is provided by Aria along with the `vrs` file? If yes, then we won't need to load the `vrs` file, right? We should be able to load the calibration information from the json.

**Comment by chpeng-fb** [comment]
Yes. The vrs calibration string can be extracted from a vrs file, which you can save as a json file.
And you can do it both ways. There is also a function that loads from the file instead `device_calibration_from_json`.
