### ISSUE TITLE
Misuse of symbols in Doc

### ISSUE THREAD

**Issue by BillMaZengou** [facebookresearch/projectaria_tools#3]
![圖片](https://github.com/facebookresearch/projectaria_tools/assets/57754488/583819a2-f7fd-48c1-acb0-80b793fc2870)

Second-line equations are wrong. should be s_a = M^{-1}_a (a - b_a)

**Comment by chpeng-fb** [comment]
Hi @BillMaZengou , thank you for catching the error. Here is the correct code convention for IMU readout. 

rectified = rectificationMatrix.inv() * (raw - bias)
raw = rectificationMatrix * rectified + bias
where raw is the actual sensor readout

https://github.com/facebookresearch/projectaria_tools/blob/main/core/calibration/ImuMagnetometerCalibration.h#L25-L31

**Comment by chpeng-fb** [comment]
Fixed by commit 93f4862bc0bf03fccba922d801c6dd9a5f04d36f 
Closing this issue, feel free to re-open if more feedback is needed.
