### ISSUE TITLE
In the ADT dataset, how do I get the labels corresponding to the 2d bounding box and why does the object_uid in the 2d_bounding_box.csv file not correspond the instance_id in the instance.json file

### ISSUE THREAD

**Issue by kb4kb5** [facebookresearch/projectaria_tools#38]

**Comment by nickcharron** [comment]
Hi @kb4kb5 , thanks for your question!

> how do I get the labels corresponding to the 2d bounding box

When querying for a 2d bounding box, you use the instance id. You can use the same id to get all the information about the object using the [get_instance_info_by_id](https://github.com/facebookresearch/projectaria_tools/blob/6dd43ae1605c6a2505910712d1a9cc175f45b3b8/projects/AriaDigitalTwinDatasetTools/python/AriaDigitalTwinDatasetToolsPyBind.h#L607) function. Please see the [adt_quickstart_tutorial](https://colab.research.google.com/github/facebookresearch/projectaria_tools/blob/1.2.0/projects/AriaDigitalTwinDatasetTools/examples/adt_quickstart_tutorial.ipynb) that demonstrates how to do this.

> why does the object_uid in the 2d_bounding_box.csv file not correspond the instance_id in the instance.json file

These should correspond to each other. Can you please elaborate on this? Or point me to an example that shows this?

**Comment by kb4kb5** [comment]
Thank you for such a thorough response!! YYour response was incredibly helpful!

**Comment by nickcharron** [comment]
You're very welcome! I assume this means your questions has been answered so I am closing this task, but please feel free to reopen if you have any more questions.
