### ISSUE TITLE
problem of visualization with python

### ISSUE THREAD

**Issue by feixue94** [facebookresearch/projectaria_tools#42]
Dear author,

could you please provide more details about how to visualize the camera trajectories and point cloud with python?
Some details (e..g., can't find viewer_aria_sensors )are missing here
https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/visualization/visualization_python#viewer_aria_sensors

**Comment by SeaOtocinclus** [comment]
Hello @feixue94 ,
Our documentation is a bit ahead of our release schedule.
But you can test them using our pre-release
`pip install projectaria-tools --pre --upgrade`

FYI you can also build our python package from master and test those on your machine:
 - [building-python-bindings-from-source-advanced-user](https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/installation/installation_python#building-python-bindings-from-source-advanced-user)

**Comment by feixue94** [comment]
Hi @SeaOtocinclus,

thanks for your reply.
