### ISSUE TITLE
[ADT] Question about the alignment of the IMU

### ISSUE THREAD

**Issue by AlbertoJaenal** [facebookresearch/projectaria_tools#46]
Dear research team

I have a question about the alignment of the IMU.
So, in [this section](https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/advanced_code_snippets/plotting_sensor_data#plotting-imu) you show how to plot the imu-left, and the result is this (where the y-axis seems to be pointing upwards from the gravity):
![image](https://github.com/facebookresearch/projectaria_tools/assets/23337326/bf94ef12-8c4e-4eab-ba52-2be7d5dc5474)

However, when looking the [coordinate system](https://facebookresearch.github.io/projectaria_tools/docs/tech_spec/hardware_spec#coordinate-systems) section, you show this image:
![image](https://github.com/facebookresearch/projectaria_tools/assets/23337326/7406e0a3-36f6-4570-9e34-3c20b8d76b71)
Where the imu-left is shown to have the x-axis pointing upwards. 

So, the IMU readings are already aligned with the scene coordinate system?
Thanks for your attention.

**Comment by SeaOtocinclus** [comment]
Hello @AlbertoJaenal you are right, the imu-left is not displayed with the right coordinate system in this image. We will fix this.

An upcoming tool in the version 1.30 will allow you to see the right coordinate system -> [viewer_aria_sensors](https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/visualization/visualization_python#run-aria-sensor-viewer) **the imu_left is indeed having Y down**.

<img width="1087" alt="image" src="https://github.com/facebookresearch/projectaria_tools/assets/74376766/3378224f-a79b-4718-867b-c1ffe74062a6">

You can already try it by installing our release candidate:
```
pip install projectaria-tools==1.3.0rc1 --upgrade
viewer_aria_sensors --vrs <YOUR_VRS_FILE>
```

Thank you for feedback and checking the data and the documentation!

**Comment by AlbertoJaenal** [comment]
Dear @SeaOtocinclus
Thanks for your quick answer! 
However, instead of the y-axis downwards, shouldn't the IMU-left have the x-axis pointing up? As shown in the transform diagram that I attached. Or at least modify it, just to be consistent with it.

**Comment by SeaOtocinclus** [comment]
We will update the diagram to reflect the same transform as the image as shared from our code sample.
@AlbertoJaenal We released our latest [version](https://github.com/facebookresearch/projectaria_tools/releases/tag/1.3.0), you can now access to the official version of `viewer_aria_sensors` ;-)

**Comment by SeaOtocinclus** [comment]
@AlbertoJaenal thank you for your feedback, we have now fixed the image in the documentation (see commit above)
https://facebookresearch.github.io/projectaria_tools/docs/tech_spec/hardware_spec#coordinate-systems
