### ISSUE TITLE
[ADT] Retrieving a List of Objects in a Specific Frame

### ISSUE THREAD

**Issue by Kasraarabi** [facebookresearch/projectaria_tools#50]
Hi!

I've encountered a scenario where I must obtain a list of objects in a specific sequence frame. Could you please confirm if this functionality exists? If so, could you guide me on how to achieve it?

Thank you for your assistance.

**Comment by SeaOtocinclus** [comment]
Hello @Kasraarabi ,
Can you elaborate if you are using an Aria Open Dataset or if you are using your own data?

In the case of using your own data, I assume you could run some 2D object detector segmentation network and so get to know if an object of the class X is present in each image with some high level of confidence.

In the case of using our Aria Open Dataset (Aria Digital Twin or Aria Synthetic Environments), there is function in the API to make query by frame, else you can project 3D object to the image by using the GT camera poses and camera intrinsics and know if an object is visible.

**Comment by Kasraarabi** [comment]
I am working with the Aria Digital Twin dataset. 

I use "gt_provider.get_synthetic_image_by_timestamp_ns()" to access a specific frame in each sequence. There is an "instances.json" file in each sequence folder. Is there a function that allows me to retrieve all visible objects in a specific frame, as listed in the JSON file for that frame?

@SeaOtocinclus

**Comment by SeaOtocinclus** [comment]
Please look to the following resources:
- python notebook (showing how to use the API)
https://facebookresearch.github.io/projectaria_tools/docs/open_datasets/aria_digital_twin_dataset/getting_started

The following function should do what you need:
```
gt_provider.get_object_3d_boundingboxes_by_timestamp_ns(
            timestamp_ns
        )
```

You can also look at our visualizers and play with them to achieve the goal you need:
https://facebookresearch.github.io/projectaria_tools/docs/open_datasets/aria_digital_twin_dataset/visualizers
See https://github.com/facebookresearch/projectaria_tools/blob/main/projectaria_tools/utils/viewer_projects_adt.py#L239C38-L239C81

**Comment by Kasraarabi** [comment]
I appreciate your comprehensive response. I've achieved what I needed with the information provided. Therefore, I'm closing this issue.
