### ISSUE TITLE
Mac OS M3 pip installation not supported

### ISSUE THREAD

**Issue by An-nay-marks** [facebookresearch/projectaria_tools#52]
While using pip to install the projectaria-tools python packages, I get the package not found error
"ERROR: Could not find a version that satisfies the requirement projectaria-tools (from versions: none)
ERROR: No matching distribution found for projectaria-tools"

info:
python 3.12.0
pip 23.3.2
platform: Mac Book Pro M3 Max, macOS Sonoma 14.1

**Comment by vijay609** [comment]
Python 3.12 is not yet supported. Are you able to try Python 3.11?

**Comment by An-nay-marks** [comment]
That worked, thank you!
