### ISSUE TITLE
Python v3.9, v3.10 problems

### ISSUE THREAD

**Issue by An-nay-marks** [facebookresearch/projectaria_tools#53]
Hi, due to other dependencies I had to downgrade to python v3.9. I also tried python 3.10 and have the following issues with both versions:
`from _core_pybinds.calibration import *  # noqa
ModuleNotFoundError: No module named '_core_pybinds'`

<img width="712" alt="image" src="https://github.com/facebookresearch/projectaria_tools/assets/87384853/20533c6a-84f9-41be-b8a2-432ab3c67f12">

This problem does not appear with python v3.11.

Thanks for your help

**Comment by SeaOtocinclus** [comment]
Thank you for your feedback. We will investigate on our side and let you know the outcome.

To help us debug, can you please tell us more about your platform?
- Linux, Mac, Mac-Silicon?

**Comment by ddetone** [comment]
Also hitting this on mac-m1:

```
adt_benchmark_dataset_downloader -c aria_digital_twin_dataset_download_urls.json -o $HOME/data/adt -d 0 1 2 3 -e
Traceback (most recent call last):
  File "/Users/ddetone/miniconda3/envs/efm3/bin/adt_benchmark_dataset_downloader", line 5, in <module>
    from projectaria_tools.projects.adt.adt_benchmark_dataset_downloader import main
  File "/Users/ddetone/miniconda3/envs/efm3/lib/python3.9/site-packages/projectaria_tools/__init__.py", line 16, in <module>
    from . import core  # noqa
  File "/Users/ddetone/miniconda3/envs/efm3/lib/python3.9/site-packages/projectaria_tools/core/__init__.py", line 21, in <module>
    from . import (  # noqa
  File "/Users/ddetone/miniconda3/envs/efm3/lib/python3.9/site-packages/projectaria_tools/core/calibration.py", line 19, in <module>
    from _core_pybinds.calibration import *  # noqa
ModuleNotFoundError: No module named '_core_pybinds'
```

**Comment by SeaOtocinclus** [comment]
Thank you @ddetone  for reporting too - mac-silicon is mac-m1 and above
The issue has been identified in our GitHub CI workflow but are unsure yet about what changed.

The cibuildwheel is keep picking the 311 pybind artefacts, despite it used to pick the python 3.X pybind artefact in the past.

**Comment by brentyi** [comment]
Possibly relevant: the new version of `fmt` (`10.2.1`) that's available on brew broke my local M1 build. Downgrading via `conda install -c conda-forge fmt==10.1.1` fixed it.

**Comment by SeaOtocinclus** [comment]
Thank you @brentyi. I also hit this issue and I have been working on a fix for the most recent version of FMT. It will be pushed soon to the repository.

Investigation:
- Issue has been confirmed to happen only for MAC GitHub CI. For some obscure reason pybind11 is not taking the python version of the `cibuildwheel` but the version of the host GitHub machine. I'm working on a fix and now trying to finalize it.

**Comment by SeaOtocinclus** [comment]
@brentyi compatibility with more recent FMT has been fixed with https://github.com/facebookresearch/projectaria_tools/commit/205e36ee10f3f9e8350a20566434ea2968e5b7ec

@An-nay-marks  Issues has been identified for building the python wheels for MacOS and a fix is almost ready. Thank you for using python 3.11 during this time.

**Comment by SeaOtocinclus** [comment]
@An-nay-marks, @brentyi the issue with the python wheels is now fixed on Pypi.

Please do run `python -m pip install projectaria_tools --upgrade` (with python or python3 depending on your python environment. 
Note that we do support macOs intel from python 3.8 to 3.12 and macOS-Silicon.arm64 from python 3.10 to 3.12

**Comment by An-nay-marks** [comment]
@SeaOtocinclus Thank you very much, works well!

**Comment by SeaOtocinclus** [comment]
Wonderful! Thank you for reporting the issue, your patience while we were looking for a fix, and for taking time to confirm that the fix is working. It is greatly appreciated!

**Comment by richardrl** [comment]
Hi I'm currently experiencing these issues following projectaria install instructions on Ubuntu 20, python 3.12.5

**Comment by richardrl** [comment]
I was finally able to get projectaria_tools installed with the following setup:
1. Micromamba new environment
2.  python3.11
3. build from source with `python3 -m pip install .`
4. python -m ipykernel install --user --name=projectarea_tools_py311 --display-name "projectarea_tools_py311"
now it works in the example jupyter notebook
