### ISSUE TITLE
alignment of multiple sequences of the same scene

### ISSUE THREAD

**Issue by feixue94** [facebookresearch/projectaria_tools#56]
Dear team,

If I collect multiple sequences of the same scene at different times and have trajectories and point clouds of these sequences from MPS, how can I align them like to the coordinate of the first sequence?

Thanks.

Best,
Fei

**Comment by vijay609** [comment]
Hello Fei,
Thank you for reaching out.
We do not have an automated way to do that today.

We are working on integrating a new MPS service that will allow users to upload a group of sequences  and get all the SLAM outputs in a common frame of reference (coordinate frame). 
We are targeting to release that in the next 1-2 months.

I hope that helps.
