### ISSUE TITLE
Broken instructions for developing new pybind

### ISSUE THREAD

**Issue by sweeneychris** [facebookresearch/projectaria_tools#57]
I'm trying to add a new class in c++ exposed via pybinds within the projectaria_tools. I am following the instructions here https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/installation/installation_python#building-python-bindings-from-source-advanced-user

but I run into an error related to rerun libraries. I think there might be some missing instructions related to the dependencies because I did not see anything related to rerun in the c++ dependencies on the website.

```
$ pip3 install --global-option=build_ext --config-settings=compile-args="-j2" .;
ERROR: Could not find a version that satisfies the requirement rerun-sdk>=0.12.0 (from projectaria-tools) (from versions: none)
ERROR: No matching distribution found for rerun-sdk>=0.12.0

**Comment by SeaOtocinclus** [comment]
Can you tell more information about your system?
- os and python versions?

From what I read it is most likely that the python compatibility can't be met on your system.
 It could be that your pip3 is pointing to a different version of python.

Once you identified your python version, you can use `python -m pip install .` or `python3 -m pip install .`

**Comment by sweeneychris** [comment]
nice `python3 -m pip install .` did indeed do the trick. it might be worth including that in the pybind instructions as well (I didnt go through the whole python install because I assumed it wasn't needed)

**Comment by SeaOtocinclus** [comment]
Thank you @sweeneychris, the issue with using the right python or pip is common, I will update the documentation with a troubleshoot section.
To be honest I now prefer to always use `pythonX -m pip` so I know which python/pip combination is used.
