### ISSUE TITLE
timestamp alignment for mic and imu data

### ISSUE THREAD

**Issue by sivannavis** [facebookresearch/projectaria_tools#58]
Hi! I'm wondering if the mic and imu data from the same vrs file is supposed to be aligned in time? For example, in this vrs file, I have the mic data as below:
<img width="1312" alt="image" src="https://github.com/facebookresearch/projectaria_tools/assets/50509896/7c4d8525-3843-471d-a011-07665ed17538">
And if I stack any of the imu data along the same timeline, it shows their overlap is really short, which doesn't align with the extracted wav file length either. e.g., we have a 10 second mic data here, but the audio itself is 3 minutes.
<img width="1268" alt="image" src="https://github.com/facebookresearch/projectaria_tools/assets/50509896/3e40f56c-2b93-4f3b-84df-098b72532ff5">

Additionally, what is the mapping between the timestamp in the mic data to the timestamp of the audio file extracted from vrs?

Could you help me on this topic? Thank you so much!

**Comment by sivannavis** [comment]
Hi @SeaOtocinclus , thanks, I've solved it, it's just the audio was truncated. However, even with all the audio & imu samples from one vrs file, they don't exactly align in time: The IMU data starts a little earlier and ends a little later than the mic data. I understand it might be different recording time and sample rates. Could you confirm if this is the case?

**Comment by SeaOtocinclus** [comment]
Yes, all timestamps are reported on the same clock, but each stream can have a slightly different time when it starts to record (https://facebookresearch.github.io/projectaria_tools/docs/data_formats/aria_vrs/timestamps_in_aria_vrs#device-timestamps).
