### ISSUE TITLE
Unit of measurement for Aria audio vs. .wav file discrepancy?

### ISSUE THREAD

**Issue by juliawilkins** [facebookresearch/projectaria_tools#59]
I am trying to understand the unit of measurement for the audio sensor data from the Aria glasses. Following [this code](https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/advanced_code_snippets/plotting_sensor_data#audio), I understand the structure of the timestamps, but am confused as to the y-axis unit. The plot says "dB", but these values are huge for dB. Comparing the values of this signal vs. loading the .wav file itself (via `extract-audio from the .vrs file), the number of samples (time) is the same, but the range of values in the wav file are more what I would expect for audio data ([-1,1] for this .wav file). What is the relationship between the unit of measurement for the sensor data and the wav data? Thanks!

Example:
![Screenshot 2024-02-05 at 11 31 01 AM](https://github.com/facebookresearch/projectaria_tools/assets/16344723/b328cb21-0c84-4146-9dd1-56ef48e94bc2)

**Comment by SeaOtocinclus** [comment]
You can find a code snippet here on how raw data can be displayed https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/advanced_code_snippets/plotting_sensor_data#audio

Regarding normalization, you can see here how we rescale them https://github.com/facebookresearch/projectaria_tools/blob/main/tools/visualization/AriaVisualizationControlAndData.cpp#L91 to the [-1, 1] range.

**Comment by juliawilkins** [comment]
Thanks @SeaOtocinclus -- for future reference if anyone finds this and has the same question -- can normalize back to match the .wav file readout in Python with:
`norm_sig = [np.round(i / (2**31 - 1 ), 8) for i in orig_sig]` (though not particularly efficient and still technically a floating point approximation.

**Comment by SeaOtocinclus** [comment]
Thank you @juliawilkins for your question and the time to share your solution for the community! Appreciated!
