### ISSUE TITLE
[ADT] Can't load `aria_trajectory.csv` with MPS

### ISSUE THREAD

**Issue by brentyi** [facebookresearch/projectaria_tools#6]
The [ADT docs](https://facebookresearch.github.io/projectaria_tools/docs/open_datasets/aria_digital_twin_dataset/data_format#aria_trajectorycsv) state, for `aria_trajectory.csv`:

> We are using the same trajectory format as [the closed loop trajectory in MPS](https://facebookresearch.github.io/projectaria_tools/docs/data_formats/mps/mps_trajectory#closed-loop-trajectory).

For the gravity vector, however, MPS expects a `gravity_{x/y/z}_world` keys ([code](https://github.com/facebookresearch/projectaria_tools/blob/befed51d91247f6bccceaf9608f61bc487295246/core/mps/TrajectoryReaders.cpp#L125-L127)), while the ADT dataset is released with `gravity_{x/y/z}` keys.

Is this intended to work out of the box? I had to adjust these keys and rebuild to get MPS working with the ADT dataset.

Thanks!

**Comment by nickcharron** [comment]
Hi @brentyi,

Thanks for bringing this to our attention! Yes, you are correct that the ADT trajectory data should share the same format as the MPS trajectory, however there is a bug in the gravity field names. 

We are working on releasing an updated dataset version with updated loaders which will fix that issue. This will be included in our next minor release planned for next week.
