### ISSUE TITLE
Getting real timestamp in Python

### ISSUE THREAD

**Issue by evfinkn** [facebookresearch/projectaria_tools#61]
Hello,

Is there anyway to get the UTC timestamp of a record (or even just an Aria VRS file) in the Python bindings? I know that Aria VRS has a time domain stream (285-1), but I can't find anything about it in the docs. Is there a reason it isn't mentioned?

**Comment by SeaOtocinclus** [comment]
Hi,
You are right we have an opportunity to enhance this documentation on [Aria Timestamp](https://facebookresearch.github.io/projectaria_tools/docs/data_formats/aria_vrs/timestamps_in_aria_vrs).

Note that we are providing some UTC value for the GPS stream https://github.com/facebookresearch/projectaria_tools/blob/599409591b434416c5d532a44b3efdb75abb79a5/core/python/SensorDataPyBind.h#L263

Else we prefer our user to always use the native time domain of the VRS stream (`timestamp_ns`).

I assume that you want a better documentation to convert the timestamp to a real clock to get the TIME (i.e 4PM:02s) at which an image as been taken, or do you want something different?

**Comment by evfinkn** [comment]
Yeah, that's what I'd like. Specifically, I have some data—including a time—from a survey taken during a recording and wasn't sure if there's any way to find in the recording when the survey was taken.

**Comment by SeaOtocinclus** [comment]
Hello @evfinkn 

Here some more information about what is doable:
- VRS is registering when a recording has started as a tag -> let's call it `vrs_recording_time`
- VRS Stream data can be relative to this timing above -> `(vrs_record_time - vrs_stream_start) + vrs_recording_time` will provide what you want

How to retrieve when a VRS file has been captured?
- as today you can use VRS binary (assuming you have it compiled)
```
# taking as example the file we are sharing here https://github.com/facebookresearch/projectaria_tools/blob/main/data/mps_sample/sample.vrs

% ./build/tools/vrs/vrs sample.vrs | grep capture_time_epoch
  Tag: capture_time_epoch = 1686767221 -- Wed Jun 14 11:27:01 2023 PDT
```
As you see this recording started on `Wed Jun 14 11:27:01 2023 PDT`

How to compute the relative timestamp for a given VRS record?
- using projectaria_tools API
`first_time = provider.get_first_time_ns(stream_id, TimeDomain.DEVICE_TIME)`
For your given recording, substract this value and then add the value from the vrs file

Adding the functionality to the real time API would make sense, let us know if you want to try to help to mockup this as contribution to the library ;-)

**Comment by SeaOtocinclus** [comment]
@evfinkn Can you close the issue, or do you want keep it open?
