### ISSUE TITLE
A typo on AEA downloader. 

### ISSUE THREAD

**Issue by georgegu1997** [facebookresearch/projectaria_tools#62]
There is a typo on the documentation [here](https://facebookresearch.github.io/projectaria_tools/docs/open_datasets/aria_everyday_activities_dataset/aea_download_dataset#step-4--download-the-sample-sequence-500mb-via-cli). Instead of `aea_benchmark_dataset_downloader`, it should be `aea_dataset_downloader` that is used everywhere else.

**Comment by nickcharron** [comment]
@georgegu1997 thank you for pointing out the typo! It has been fixed in https://github.com/facebookresearch/projectaria_tools/commit/1784868636914fd5b92e687bfdccb215a88f05f1
