### ISSUE TITLE
How can I get depth image base on the "Slam-left" and "Slam-right" camera on EgoExo4d datasets?

### ISSUE THREAD

**Issue by Hoyyyaard** [facebookresearch/projectaria_tools#64]

**Comment by SeaOtocinclus** [comment]
Hello @Hoyyyaard , please add some description to your question.

I believe you are asking how to retrieve a depth map from a binocular image rig.
- to do that I would advise you to look at method to compute disparity from stereo images

Note that, ProjectAria Tools provides functions to retrieve the camera parameters (intrinsics and extrinsics) so you can get to know the baseline and rectify the image if required.

[Calibration documentation](https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/core_code_snippets/calibration)
[Image undistortion documentation]( https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/advanced_code_snippets/image_utilities#image-undistortion)

**Comment by SeaOtocinclus** [comment]
@Hoyyyaard  do you still have questions following our reply, else can you close the issue, thank you.

**Comment by Hoyyyaard** [comment]
> @Hoyyyaard do you still have questions following our reply, else can you close the issue, thank you.

Thanks so much for your reply

**Comment by banafshebamdad** [comment]
Hello,
First of all, thank you for the incredible tools and support!
I am currently working on a project that involves generating depth maps using stereo images from Meta Aria glasses. While the tools provided are extremely useful, I noticed that there isn't a service for generating depth maps directly.
I wanted to inquire if there are any plans to add a service for depth map generation in MPS in the near future.
Thank you for your consideration,
Banafshe Bamdad
