### ISSUE TITLE
ADT: are object models (e.g., CAD) provided?

### ISSUE THREAD

**Issue by jcorsetti** [facebookresearch/projectaria_tools#66]
Hi, thanks for the release of this dataset.
I was wondering whether some model representation of the objects in the dataset, like a CAD model, are provided.
From Section 3.1 (object digitazion) of the ADT paper an acquisition process is described.
Did I missed them or they are actually not provided?

Thanks

**Comment by nickcharron** [comment]
Hi @jcorsetti, thanks for your question. No you didn't miss anything, we did not release the models. This is actually a common request we have been getting from the community. We are working on a solution for releasing the 3D models for all ADT objects, but it will take some time. I will respond to this issue when/if we are able to release the models.

**Comment by nickcharron** [comment]
Hi @jcorsetti, I am closing this issue, but please feel free to re-open if you have any follow up questions. Thanks!

**Comment by nickcharron** [comment]
Hi @jcorsetti, just letting you know that we recently released the object models for ADT. See the documentation here: https://facebookresearch.github.io/projectaria_tools/docs/open_datasets/aria_digital_twin_dataset/object_models

Hope this isn't too late :)
