### ISSUE TITLE
Error(501) after processing MPS ET data

### ISSUE THREAD

**Issue by matteominardi** [facebookresearch/projectaria_tools#70]
I activate correctly the environment using:
`source $HOME/projectaria_tools_python_env/bin/activate`

When requesting the MPS services using:
`aria_mps single -i myFolderWithTheVRS/`

The tool uploads my VRS, performs the healthcheck, the encryption, the upload and the processing without any problems, but when it comes to the download it says Error(501), after almost 15 minutes of processing.

For the recording, I am using profile 5 and I'm only interested in the Eye Gaze data (in fact, I get Error(102) for SLAM but that is obviously not a problem). 

The json health-check files that I obtain seem to not have any issues, even when checking the integrity of the recordings from the Aria app, everything seems correct.

Here are the health check files I get during the process:
- json downloaded from the glasses, along with the vrs, right after the recording session:
[latest.vrs.json](https://github.com/facebookresearch/projectaria_tools/files/14693251/latest.vrs.json)
- json files obtained during the processing of the MPS cloud tool 
[vrs_health_check.json](https://github.com/facebookresearch/projectaria_tools/files/14693211/vrs_health_check.json)
[vrs_health_check_slam.json](https://github.com/facebookresearch/projectaria_tools/files/14693212/vrs_health_check_slam.json)

I was able to obtain the data correctly up until last week.
It has not been working just for the last 2-3 days, to my knowledge. I tried multiple times also with different recordings. 

I also already tried updating the Aria software this morning. 

Please let me know if you need any additional information or if I'm doing anything wrong, thanks in advance.

**Comment by matteominardi** [comment]
UPDATE:
I tried again this morning, after seeing the new released version, and the problem persists with no differences: everything as expected up until a few minutes of processing, when the download of the results should probably begin.

For context, for today's test I recorded a video called `updated15`.
The video has been recorded again with `profile 5`.

Here are some more files that might help:
- Log files from the CLI (I tried running it twice for the same recording)
[2024-03-22-10-29-53.log](https://github.com/facebookresearch/projectaria_tools/files/14720744/2024-03-22-10-29-53.log)
[2024-03-22-10-48-18.log](https://github.com/facebookresearch/projectaria_tools/files/14720746/2024-03-22-10-48-18.log)
- Healthchecks:
[vrs_health_check.json](https://github.com/facebookresearch/projectaria_tools/files/14720763/vrs_health_check.json)
[vrs_health_check_slam.json](https://github.com/facebookresearch/projectaria_tools/files/14720764/vrs_health_check_slam.json)
- Again, no `summary.json` is obtained because it breaks before the final download
- Screenshot of the problem
![screenshot](https://github.com/facebookresearch/projectaria_tools/assets/110735780/db8880b7-1931-4274-a1a5-3ae1ee10c29c)

Thanks for the attention, and again please let me know if there is anything else that you need or if I'm doing something wrong.

**Comment by SeaOtocinclus** [comment]
Hello @matteominardi, @vijay609 will comment back soon regarding your issue.

**Comment by vijay609** [comment]
Hey @matteominardi ,
We found an issue on the MPS backend and we have resolved it.
Can you please retry one more time ?

**Comment by matteominardi** [comment]
> Hey @matteominardi , We found an issue on the MPS backend and we have resolved it. Can you please retry one more time ?

Hello, I will retry again on Monday. In the meantime, thanks for the answer.

**Comment by matteominardi** [comment]
It works now so I'm closing the issue.
Thank you @SeaOtocinclus @vijay609 for the effort!
