### ISSUE TITLE
ADT 3D Object Detection Challenges Evaluation Blank

### ISSUE THREAD

**Issue by chahyon-ku** [facebookresearch/projectaria_tools#71]
I have made a few submissions to phase 3 (few-shot validation) of the challenge, but the "result file" and "stdout file" (visible from the "my submissions" tab) are both blank.
When I make my submission public and check on the leaderboard, I see that all metrics are 0.

However, I'm unsure whether the metrics are 0 because not a single prediction matched the annotation or because the evaluation script is just not spitting out any results (as seen in the blank "result file").
I would like to think that I at least retrieved and matched the pose from the initial 5 seconds properly, but there's still some room for error I guess.

I am doing something along the lines of
```python
for img_timestamp_ns in provider.get_aria_device_capture_timestamp_ns(stream_id):
    image_with_dt = provider.get_aria_image_by_timestamp_ns(img_timestamp_ns, stream_id)
    bbox2d_with_dt = provider.get_object_2d_boundingboxes_by_timestamp_ns(img_timestamp_ns, stream_id)
    bbox3d_with_dt = provider.get_object_3d_boundingboxes_by_timestamp_ns(img_timestamp_ns)
    aria3d_with_dt = provider.get_aria_3d_pose_by_timestamp_ns(img_timestamp_ns)
    assert image_with_dt.is_valid(), "Image not valid!"
    assert bbox2d_with_dt.is_valid(), "2D bounding box is not available"
    assert bbox3d_with_dt.is_valid(), "3D bounding box is not available"
    assert aria3d_with_dt.is_valid(), "3D pose is not available"
    
    image_path = os.path.join(sequence_cache_dir, f'imgs/{img_timestamp_ns}.png')
    # if image and bbox2d are close in time
    if (
            abs(bbox2d_with_dt.dt_ns()) < 200000 and
            abs(bbox3d_with_dt.dt_ns()) < 200000 and
            abs(aria3d_with_dt.dt_ns()) < 200000
    ):
```
to match and save the annotations in the frame's (image's) timestamp, but maybe this logic is critically off?

My method (https://github.com/facebookresearch/projectaria_tools/assets/8120297/cf5e0b00-0cfd-499c-88ae-fd9916dd89b6) is barely working, so I'll be happy if I can just get one legit submission in before it's due for experience's sake :)
Thanks for the awesome dataset, challenge, and any help in advance!

**Comment by chahyon-ku** [comment]
Also, did the challenge finish early?
It seems like it's inactive on eval AI because it finishes 12AM 03/22 (Fri) instead of 11:59PM 03/22 (Fri).

**Comment by chahyon-ku** [comment]
Hey, just a friendly ping, because it's nearing the end of the day here.
There should still be about 9 hours left according to the announced official due date, but the eval AI challenge is still inactive and won't let me submit...
I know it's the last day, but it'd be super helpful if you could help me with this :)

**Comment by nickcharron** [comment]
Hi @chahyon-ku, I am looking into extending the deadline now. In the mean time, I think you may have used the wrong prototype names. They should be WorkoutDumbbell_Proto and WaterPitcher_Proto

**Comment by chahyon-ku** [comment]
Ah makes sense, thank you so much!
I assumed no "_Proto" because Apartment_release_challenge_example contained prototypes like "ChoppingBoard" and "WhiteUtensilTray" in "submissions_example/Apartment_release_challenge_example.csv", but that example must have been for phase 1/2.

**Comment by nickcharron** [comment]
@chahyon-ku are you able to submit now?

**Comment by chahyon-ku** [comment]
![Screenshot from 2024-03-22 17-08-17](https://github.com/facebookresearch/projectaria_tools/assets/8120297/d106b83b-3d61-44f8-a2d7-df02ff8e4388)
Same issue with same end datetime I believe.

**Comment by nickcharron** [comment]
I see.. I'm not the maintainer of this so it seems I can't update it. I have contacted the maintainers, hopefully they get back to me soon. But I'm sure we can extend it so that you can submit, please don't stress about the time! Sorry for the inconvenience.

**Comment by chahyon-ku** [comment]
That's awesome :) Thank you so much for the help and have a great weekend!

**Comment by nickcharron** [comment]
It should be updated now. Please let me know if you have any other issues, otherwise, please close the issue. Thank you for participating in our challenge!

**Comment by chahyon-ku** [comment]
Thanks for that! I ended up submitting later that night, but the submission seems to be stuck at the "submitted" stage and neither "finished" or "failed." Is this also likely some formatting issue of the submission?
It's so unforunate that the competition finished so early :/ I only found out about the competition through the EgoVis Workshop posting and there's still so much time until the workshop...

**Comment by nickcharron** [comment]
Glad to hear you were able to submit! We confirmed that we did receive your submission. The server gets shut down after the deadline so maybe it didn't have time to complete the evaluation before it was shut down. 

Sorry to hear you only found out about the challenge recently. We do try to announce these challenges at the major conferences (e.g., ECCV, ICCV, CVPR), but it is still hard to get the reach that we would like. Please keep an eye out for future challenges at projectaria.com, or sign up for our newsletter on the home page to make sure you don't miss anything!

Thanks again for participating! Closing this issue, but please feel free to add more comments or reopen if you have anything else you'd like to discuss.
