### ISSUE TITLE
[ASE] Will 3D meshes be released?

### ISSUE THREAD

**Issue by zjwzcx** [facebookresearch/projectaria_tools#73]
Thank you all for your awesome project! 
I'm curious about whether you will release the 3D meshes, which is quite helpful for my research about embodied AI. If so, when will you release them?

**Comment by suvampatra** [comment]
First of all I wish to thank you for using the dataset and hope its useful.
At the moment, we do not have a plan to release the 3D meshes. But that might change in the future. 
To stay informed, I would request you to subscribe to the news updates via email at https://www.projectaria.com/
