### ISSUE TITLE
How to get wrist & palm data from Aria Everyday Activities dataset

### ISSUE THREAD

**Issue by JoaoM07** [facebookresearch/projectaria_tools#74]
Hi,
The MPS sample data from the Project Aria tools comes with a CSV for hand tracking. Is it possible to get hand tracking (i.e. wrist and palm location)for the Aria Everyday Activities dataset?

**Comment by nickcharron** [comment]
Hi @JoaoM07, thanks for your question and your interest in the Aria Everyday Activities dataset! Hand tracking is a relatively new output from MPS so it was not generated at the time we released AEA. We have added this feature request to our queue, and we can inform you when/if it becomes available. In the meantime, if you have an Aria Research Kit, you can generate your own MPS results (including wrist and palm data) using our CLI or on-demand service. If you do not, you can apply here: https://www.projectaria.com/research-kit/.

**Comment by nickcharron** [comment]
@JoaoM07 closing this task but please feel free to re-open if you have any additional comments or questions!
