### ISSUE TITLE
Command line cli SLAM crashing

### ISSUE THREAD

**Issue by SimarKareer** [facebookresearch/projectaria_tools#77]
<img width="1498" alt="image" src="https://github.com/facebookresearch/projectaria_tools/assets/15113178/c6d91c77-342f-4f9e-808a-60eb8046200b">

I'm having an issue with running `aria_mps single <folder name>`. After the hashing step I get error 501.  In this case it seems to only happen for my larger demos but not the smaller one.  Any idea on why this might be happening?  My demo was recorded via profile 15.  And I'm using the most recent PyPi release 1.5.0 of projectaria-tools

**Comment by SeaOtocinclus** [comment]
Error codes are detailed here https://facebookresearch.github.io/projectaria_tools/docs/ARK/mps/mps_troubleshooting#error-codes
Error 501 seems related to a server side failures. I will forward to the team and they will come back to you.

**Comment by SimarKareer** [comment]
Great thank you!

**Comment by SimarKareer** [comment]
@SeaOtocinclus any luck on this by chance?  By the way the same demos succeeds when I upload via the desktop app.

**Comment by vijay609** [comment]
@SimarKareer 
501 refers to Unknown Error on the backend.
Can you please share the MPS log file for this failure? This will help us investigate the failure.

**Comment by SimarKareer** [comment]
[err_log.txt](https://github.com/facebookresearch/projectaria_tools/files/15002349/err_log.txt)
Here it is, thank you

**Comment by vijay609** [comment]
Thanks @SimarKareer 
I have made some changes on the backend. Can you please run the cli again with `--retry-failed` parameter?

**Comment by SimarKareer** [comment]
[err_log2.txt](https://github.com/facebookresearch/projectaria_tools/files/15015968/err_log2.txt)
Hi, I'm still getting an error on those demos actually

**Comment by vijay609** [comment]
Hey @SimarKareer 
I dug into the issue and I know what is causing the failure. The proper fix will probably take some time, but until then I have the ability to manually patch the failure.
I did that for your requests and the results are ready.
If your run the CLI again, it should download the successful slam results from your last request.

If you run into this issue again, please feel free to reach out and I will manually patch it. Once we release a proper fix, this should be more smooth.
I apologize for the inconvenience.

**Comment by SimarKareer** [comment]
Sorry somehow didn't get a notification!  Thanks for digging into this.  For now I can continue to collect demos <5min since those seem to not crash.  Is the proper fix coming soon, or is that more of a ways out?  Thanks!

**Comment by vijay609** [comment]
Resolved

**Comment by SimarKareer** [comment]
@vijay609 Sorry to bother, but a few more of my runs have failed.  Would you mind fixing these on the backend too?
<img width="2011" alt="image" src="https://github.com/facebookresearch/projectaria_tools/assets/15113178/06c41215-5bc7-47ac-bc15-b6e6ccfa4ed8">

**Comment by vijay609** [comment]
@SimarKareer I believe this is not resolved?

**Comment by asbe** [comment]
@vijay609 I observe the same error (501) as @SimarKareer on Eye Gaze and SLAM for one of my VRS. It is a fairly large file (20GB), is that the underlying issue?

**Comment by SimarKareer** [comment]
@vijay609 Can we reopen this issue?
