### ISSUE TITLE
personalized_eye_gaze.csv has not been generated

### ISSUE THREAD

**Issue by haoyulee95** [facebookresearch/projectaria_tools#79]
Hello Team Aria,

I recently attempted to generate the personalized eye gaze CSV file following the steps outlined on this page: https://facebookresearch.github.io/projectaria_tools/docs/ARK/mps/eye_gaze_calibration
Despite following the instructions, I encountered an issue where the expected file was not generated. Upon inspecting the summary.json file, I found only the following line:{"GazeInference": {"status": "SUCCESS", "message": ""}, "version": "3.0"} This differs from what is described on the documentation page.

Thank you for your patience.

**Comment by vijay609** [comment]
Did your vrs file contain in-session calibration?
In order to be able to generate personalized eye gaze, the vrs file needs
to have calibration information.
https://facebookresearch.github.io/projectaria_tools/docs/ARK/mps/eye_gaze_calibration

**Comment by vijay609** [comment]
Hello Hao,
If you followed the instructions and there is no personalized eye gaze, it
usually means that the calibration data was not good or missing.
Can you please do a new recording and run aria_mps cli on it and then share
the log file with me?

This would help with next steps of debugging.
You can also reach out to us on Discord for a quicker turn around time.

**Comment by haoyulee95** [comment]
Hello,

Thanks for the reply. The log is as follows.

I hope you have a nice weekend.

**Comment by vijay609** [comment]
@haoyulee95 
I don't see the log file attached. Can you please upload it to google drive and share it here ?

**Comment by vijay609** [comment]
@haoyulee95 
Are you able to submit the request again?

**Comment by jacksalici** [comment]
Is the issue solved? I've also submitted yesterday a calibrated (following the tutorial) VRS but the output contains only the general eye gaze...
