### ISSUE TITLE
[ADT] RGB Camera extrinsic relative to the world

### ISSUE THREAD

**Issue by alonime** [facebookresearch/projectaria_tools#8]
Hey, and thanks for the datasets and the challenge.
I tried to build the RGB-camera trajectory relative to the world coordinates and I'm getting the orientation wrong. 

I'm not sure what  `aria_3d_pose`gives, therefore I used the `aria_trajectory.csv` but the timestamps are not registered to images timestamps so I took the closest. However, the orientation is way off even without taking into acuunt the transition from the device to the camera ('aria_transform_device_camera')

Can you please give details on how to extract the camera trajectory in the right way?

**Comment by YLouWashU** [comment]
Hey Alonime, thanks for your interest in projectaria_tools! 

`aria_3d_poses` from `AriaDigitalTwinDataProvider.get_aria_3d_pose_by_timestamp()` would give you `T_World_Device` (meaning a transformation from Device to World). And `Device` here means a "local coordinate system" on the Aria glass itself. Therefore, you would need an addtional `T_Device_RgbCamera = AriaDigitalTwinDataProvider.get_aria_T_Device_Camera("214-1")` to obtain this extra pose. Then you can get `T_World_RgbCamera = T_World_Device * T_Device_RgbCamera` as the trajectory of the RGB camera pose. 

If you still run into issues, feel free to paste any code snippet here and we can help you find the correct way to do what you wish to. Thanks!

**Comment by YLouWashU** [comment]
Oh and BTW we rolled out a code release to fix a wrong header label in the `aria_trajectory.csv` file, which might be related to what you are seeing: [release note](https://github.com/facebookresearch/projectaria_tools/releases/tag/1.1.0), especially if you decided to parse the csv file on your own. To fix this, you can re-download the v1.1 ADT datasets and pull the most recent github codebase to see if the issue persists. Thanks!

**Comment by alonime** [comment]
Thank you @YLouWashU !! The last release did solve the problem. So I'm closing this issue.
BTW, even now when the camera trajectory make sense I do need to refine the translation and rotation for successful  reconstruction.

**Comment by SeaOtocinclus** [comment]
Can you elaborate on your last point:
- What do you mean by refining the translation/rotation?
- What do you mean by reconstruction (reconstructing a point cloud, mesh using X)?

Do note that the RGB camera is a RS (Rolling Shutter) camera, so if you attempts reconstruction task you could have more success using the GRAY RGB GS (Global Shutter) cameras.

**Comment by alonime** [comment]
Hey @SeaOtocinclus,

Sure, 
1. I mean that the camera's extrinsic matrices aren't accurate enough.
2. Yes eventually to build PC by training NeRF. 

So in order that the Nerf model will converge the extrinsic matrices need to be optimized.

**Comment by SeaOtocinclus** [comment]
Thank you for coming back to us @Davidyao99 ,
1. I extracted the frames from the videos. How do I map the timestamp to the frames?
  I would advise you to stick to VRS if you can, so you would always be able to map an image to a timestamp
    - if you want to stick to video frame, I would advise you to have a mapping (frameId, Timestamp) in a file that you use

2. StreamId
  StreamId is an object allowing to specify with Stream you want to work with. You can build one easily using the StreamId object (`stream_id = StreamId("214-1")  # use RGB camera for testing`)
  - You can check our jupyter notebooks to learn about to master our API https://github.com/facebookresearch/projectaria_tools#interactive-python-notebook-playground-google-colab

Let us know if you have sufficient feedback or still have questions.
