### ISSUE TITLE
MPS has no module named utils

### ISSUE THREAD

**Issue by suraj-avataar** [facebookresearch/projectaria_tools#87]
I was following the instructions provided [here](https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/core_code_snippets/mps) to get the closed loop trajectory.  However, I face a no module found error

```
----> 1 from projectaria_tools.core.mps.utils import get_nearest_pose

ModuleNotFoundError: No module named 'projectaria_tools.core.mps.utils'; 'projectaria_tools.core.mps' is not a package
```
Upon checking out the github code, there is indeed no such module, I am not sure if the docs need to be updated / there is a version mismatch. Would help if pointed in the right direction

**Comment by SeaOtocinclus** [comment]
Hi @suraj-avataar  can you tell us which version of projectaria_tools do you have?
Else you can update your existing version to match to the last one by running:
`python3 -m pip install projectaria_tools --upgrade`

There is indeed a projectaria_tools.core.mps.utils module that is here https://github.com/facebookresearch/projectaria_tools/tree/main/projectaria_tools/core/mps/utils.py

**Comment by suraj-avataar** [comment]
Thank you, it works after updating. I had 'projectaria-tools-1.2.0' before.

**Comment by SeaOtocinclus** [comment]
I wish you happy experimenting with the new features ;-)
