### ISSUE TITLE
downloaded trajectory zipfile is empty 

### ISSUE THREAD

**Issue by feixue94** [facebookresearch/projectaria_tools#88]
Dear team,

Sometimes the downloaded trajectory zipfile is empty. Do you know what happed?

![image](https://github.com/facebookresearch/projectaria_tools/assets/49382877/93565877-7137-4508-acb1-7d328148cae7)

**Comment by vijay609** [comment]
Can you please restart the app and then try downloading? i see the file on the backend.

**Comment by feixue94** [comment]
Thanks for your reply. I tried several times and every time it shows the trajectory is successfully downloaded but it is empty

**Comment by feixue94** [comment]
![屏幕截图 2024-05-01 133406](https:
[marys_regenst_marys_20240429_Trajectory.zip](https://github.com/facebookresearch/projectaria_tools/files/15177693/marys_regenst_marys_20240429_Trajectory.zip)
//github.com/facebookresearch/projectaria_tools/assets/49382877/6279f2c6-e51f-4166-818d-abe99f65f0e0)

The downloading process looks normal while it fails to write the data into disk. Is it too large?

**Comment by feixue94** [comment]
I'm using Multi SLAM request and it works now.
