### ISSUE TITLE
Point cloud computation

### ISSUE THREAD

**Issue by VladimirYugay** [facebookresearch/projectaria_tools#93]
Hey there,

I want to use aria ASE data. I read the RGB and depth as explained in the `ase_tutorial_notebook`. To compute a point cloud of interest it seems that I need to undistort both image and depth first, otherwise geometry in my point clouds is "bended".

1. I used the functions described [here](https://github.com/facebookresearch/projectaria_tools/blob/main/projectaria_tools/utils/calibration_utils.py) to undistort the image successfully. However, for adjusting the calibration after rotating the image to the right gives me an error: `AttributeError: module 'projectaria_tools.core.calibration' has no attribute 'rotate_camera_calib_cw90deg'`. Is it the tools version I'm missing?

2. How to undistort the depth map? I tried using the same functions as for image, but it doesn't work.

Thanks!

**Comment by AnarchistKnight** [comment]
Have a good day.

Did you successfully reconstruct the point cloud? To rectify the distorted images, you may search "Undistort an image" in projectaria_tools/core/examples/dataprovider_quickstart_tutorial.ipynb. I use that part of code to successfully undistort rgb and depth. 

But I failed to reconstruct the scene from AriaSyntheticEnvironment dataset. I read tx, ty, tz, qx, qy, qz, qw from trajectory.csv to compute the camera_to_world matrix. And then use open3d to reconstruct the scene. The rectified image is
![image](https://github.com/user-attachments/assets/1ef6e735-32b6-43a5-a2a2-1037a7bf79d2) and the reconstructed scene is 
![image](https://github.com/user-attachments/assets/7c0de76a-e0dd-46d5-8170-f6d6c386550c). You can see difference frame does not match with each other.

I would like to uncover more details and share the code if you would like to discuss.
