### ISSUE TITLE
Depth map computation

### ISSUE THREAD

**Issue by VladimirYugay** [facebookresearch/projectaria_tools#94]
Hey there,

For the ASE data, it is mentioned [here](https://facebookresearch.github.io/projectaria_tools/docs/open_datasets/aria_synthetic_environments_dataset/ase_data_format) that the depth maps are depth values along pixel ray direction. First, I rectified color and depth images as described [here](https://github.com/facebookresearch/projectaria_tools/issues/11). Now how can I compute the "normal" depth map? Is it fair to assume that I can use this formula:

![image](https://github.com/facebookresearch/projectaria_tools/assets/12258972/9780953c-091f-406b-b9ac-69d931d6a79d)

Also, adjusting the calibration after rotating the image to the right gives me an error: `AttributeError: module 'projectaria_tools.core.calibration' has no attribute 'rotate_camera_calib_cw90deg'` if I use this [script](https://github.com/facebookresearch/projectaria_tools/blob/main/projectaria_tools/utils/calibration_utils.py)).  Is there a function to do that in the toolbox?

**Comment by SeaOtocinclus** [comment]
In order to use the 'rotate_camera_calib_cw90deg' you need a pre-release version of our pypi archive. You can access it by using `pip install projectaria-tools==1.5.1a1 --upgrade`

Regarding the normal depth map I will let @suvampatra add comments

**Comment by suvampatra** [comment]
Sorry  for the delayed response. Thanks @SeaOtocinclus for clarifying some of the doubts. 

As for the range map -> depth map conversion, I see you have already figured it out and thanks for sharing it with us. 

As for the coordinate systems for the data please have a look at https://facebookresearch.github.io/projectaria_tools/docs/data_formats/coordinate_convention/3d_coordinate_frame_convention. This should give you a fair understanding of the coordinate system of the data.

**Comment by suvampatra** [comment]
I think the questions have been answered, and I don't see any new questions. Please feel free to reopen it, if you have more questions
