### ISSUE TITLE
audio data chunk, not same

### ISSUE THREAD

**Issue by lixinghe1999** [facebookresearch/projectaria_tools#97]
Dear all, 

I use the following code from 
https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/advanced_code_snippets/plotting_sensor_data to extract audio. To always access 1-second data, I need to first convert the timestamp to the corresponding index, which means I need to know the length of each data chunk. (e.g., timestamp/length of data chunk)

According to the documentation, the data chunk should always be 4096. However, I observed both the 2048 and 4096 data chunks. As a solution, I inspect the first chunk's length to determine (on the fly) it rather than hard-code it. Right now, the code doesn't crash, but I am still confused about the misalignment of the data chunk length.

**Comment by chpeng-fb** [comment]
Hi @lixinghe1999, 

We indeed have two different audio sizes. The documentation is an example to demonstrate how to extract and visualize the data. 
You should be able to get the `capture_timestamps_ns` for each sample in a single data chunk to make sense of how was the data sampled. 

Hope this helps.

**Comment by lixinghe1999** [comment]
Thank you for getting back to me.

I have a follow-up question: since I am working on multi-mic processing, can you provide the exact location of each microphone?
I understand that the below figure shows the location, but an accurate coordinate may be better.
![image](https://github.com/facebookresearch/projectaria_tools/assets/60444469/578aa2fe-4251-4340-a1de-5a5c2f977aae)

Also, if the stereo recording is on, which two microphones are selected?

**Comment by chpeng-fb** [comment]
Hi @lixinghe1999 , 

Unfortunately, the current interface does not provide the microphone locations since they are not calibrated.

**Comment by SeaOtocinclus** [comment]
Microphones location can be retrieved, see this example https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/visualization/visualization_python#run-aria-sensor-viewer
![image](https://github.com/facebookresearch/projectaria_tools/assets/74376766/b00bddf1-c85d-4791-8eca-06b090514e60)
See here on how to retrieve the microphone positions https://github.com/facebookresearch/projectaria_tools/blob/main/projectaria_tools/utils/viewer_aria_sensors.py#L85

**Comment by lixinghe1999** [comment]
thanks for answering.

I use the following code from "viewer_aria_sensors.py" to get the locations.
```
 provider = data_provider.create_vrs_data_provider(vrs)
 mic_labels = device_calibration.get_microphone_labels()
 print(f"Log {len(mic_labels)} Microphones")
 import numpy as np
 for mic in mic_labels:  # Note: Only defined in CAD calibration
      T_device_sensor = device_calibration.get_transform_device_sensor(mic, True)
      translation=T_device_sensor.translation()
      print(translation)
```
If others want to skip it, the answer is 
```
np.c_[[ 0.03546091, -0.09185805, -0.07152638], [-0.00630641, -0.054662, -0.03122935],
 [ 0.03252111, -0.01865076, -0.01542986], [-0.00923072, -0.00177898, -0.00708757],
 [-0.0068401,  -0.10160788, -0.07526885], [-0.00162908,  0.06371858, -0.08164837],
 [ 0.00298007, -0.05102968, -0.16957706]]
```

**Comment by lixinghe1999** [comment]
yes, thank you

> Do you have all your questions answered?

**Comment by SeaOtocinclus** [comment]
Closing the issue since all questions have been answered.
